import type { Card } from '../../../shared/types';

export const DWARF_COLLECTION = {
  id: 'dwarf',
  name: 'Anões',
  description: 'O Baluarte de Pedra — Anões'
};

export const DWARF_CARD_CATALOG = [
  {
    "id": "dwa_001_bhal_dur_o_sentinela_de_ferro",
    "name": "Bhal-Dur, o Sentinela de Ferro",
    "type": "DEFENDER",
    "race": "dwarf",
    "class": null,
    "cost": 4,
    "abilities": [
      "taunt"
    ],
    "text": "Prov. Cura 2",
    "rarity": "COMMON",
    "image_url": null,
    "effects": [],
    "default_unlocked": true,
    "is_active": true,
    "collection_id": "dwarf",
    "visual_auras": [],
    "attack": 2,
    "defense": 6
  },
  {
    "id": "dwa_002_mestre_runico_de_khazad",
    "name": "Mestre Rúnico de Khazad",
    "type": "DEFENDER",
    "race": "dwarf",
    "class": null,
    "cost": 3,
    "abilities": [],
    "text": "—",
    "rarity": "COMMON",
    "image_url": null,
    "effects": [],
    "default_unlocked": true,
    "is_active": true,
    "collection_id": "dwarf",
    "visual_auras": [],
    "attack": 1,
    "defense": 4
  },
  {
    "id": "dwa_003_thrain_o_rei_sob_a_montanha",
    "name": "Thrain, o Rei sob a Montanha",
    "type": "DEFENDER",
    "race": "dwarf",
    "class": null,
    "cost": 8,
    "abilities": [
      "taunt"
    ],
    "text": "Prov",
    "rarity": "COMMON",
    "image_url": null,
    "effects": [],
    "default_unlocked": true,
    "is_active": true,
    "collection_id": "dwarf",
    "visual_auras": [],
    "attack": 5,
    "defense": 10
  },
  {
    "id": "dwa_004_engenheiro_de_muralhas",
    "name": "Engenheiro de Muralhas",
    "type": "DEFENDER",
    "race": "dwarf",
    "class": null,
    "cost": 2,
    "abilities": [
      "taunt"
    ],
    "text": "Prov",
    "rarity": "COMMON",
    "image_url": null,
    "effects": [],
    "default_unlocked": true,
    "is_active": true,
    "collection_id": "dwarf",
    "visual_auras": [],
    "attack": 1,
    "defense": 3
  },
  {
    "id": "dwa_005_forjador_de_almas_ancestrais",
    "name": "Forjador de Almas Ancestrais",
    "type": "DEFENDER",
    "race": "dwarf",
    "class": null,
    "cost": 5,
    "abilities": [],
    "text": "+1 card",
    "rarity": "COMMON",
    "image_url": null,
    "effects": [],
    "default_unlocked": true,
    "is_active": true,
    "collection_id": "dwarf",
    "visual_auras": [],
    "attack": 3,
    "defense": 5
  },
  {
    "id": "dwa_006_escavador_de_tuneis_profundos",
    "name": "Escavador de Túneis Profundos",
    "type": "DEFENDER",
    "race": "dwarf",
    "class": null,
    "cost": 3,
    "abilities": [
      "rush"
    ],
    "text": "Ini",
    "rarity": "COMMON",
    "image_url": null,
    "effects": [],
    "default_unlocked": true,
    "is_active": true,
    "collection_id": "dwarf",
    "visual_auras": [],
    "attack": 2,
    "defense": 4
  },
  {
    "id": "dwa_007_clerigo_da_pedra_sagrada",
    "name": "Clérigo da Pedra Sagrada",
    "type": "DEFENDER",
    "race": "dwarf",
    "class": null,
    "cost": 4,
    "abilities": [],
    "text": "Cura 4",
    "rarity": "COMMON",
    "image_url": null,
    "effects": [],
    "default_unlocked": true,
    "is_active": true,
    "collection_id": "dwarf",
    "visual_auras": [],
    "attack": 1,
    "defense": 7
  },
  {
    "id": "dwa_008_berserker_de_granito",
    "name": "Berserker de Granito",
    "type": "DEFENDER",
    "race": "dwarf",
    "class": null,
    "cost": 6,
    "abilities": [
      "rush"
    ],
    "text": "Ini",
    "rarity": "COMMON",
    "image_url": null,
    "effects": [],
    "default_unlocked": true,
    "is_active": true,
    "collection_id": "dwarf",
    "visual_auras": [],
    "attack": 4,
    "defense": 8
  },
  {
    "id": "dwa_009_estrategista_do_cla_de_prata",
    "name": "Estrategista do Clã de Prata",
    "type": "DEFENDER",
    "race": "dwarf",
    "class": null,
    "cost": 3,
    "abilities": [],
    "text": "—",
    "rarity": "COMMON",
    "image_url": null,
    "effects": [],
    "default_unlocked": true,
    "is_active": true,
    "collection_id": "dwarf",
    "visual_auras": [],
    "attack": 2,
    "defense": 5
  },
  {
    "id": "dwa_010_guardiao_do_portao_leste",
    "name": "Guardião do Portão Leste",
    "type": "DEFENDER",
    "race": "dwarf",
    "class": null,
    "cost": 2,
    "abilities": [
      "taunt"
    ],
    "text": "Prov",
    "rarity": "COMMON",
    "image_url": null,
    "effects": [],
    "default_unlocked": true,
    "is_active": true,
    "collection_id": "dwarf",
    "visual_auras": [],
    "attack": 0,
    "defense": 6
  },
  {
    "id": "dwa_011_alquimista_da_fuligem",
    "name": "Alquimista da Fuligem",
    "type": "DEFENDER",
    "race": "dwarf",
    "class": null,
    "cost": 3,
    "abilities": [],
    "text": "—",
    "rarity": "COMMON",
    "image_url": null,
    "effects": [],
    "default_unlocked": true,
    "is_active": true,
    "collection_id": "dwarf",
    "visual_auras": [],
    "attack": 2,
    "defense": 3
  },
  {
    "id": "dwa_012_defensor_da_forja_eterna",
    "name": "Defensor da Forja Eterna",
    "type": "DEFENDER",
    "race": "dwarf",
    "class": null,
    "cost": 5,
    "abilities": [],
    "text": "—",
    "rarity": "COMMON",
    "image_url": null,
    "effects": [],
    "default_unlocked": true,
    "is_active": true,
    "collection_id": "dwarf",
    "visual_auras": [],
    "attack": 3,
    "defense": 7
  },
  {
    "id": "dwa_013_oraculo_das_rochas",
    "name": "Oráculo das Rochas",
    "type": "DEFENDER",
    "race": "dwarf",
    "class": null,
    "cost": 4,
    "abilities": [],
    "text": "—",
    "rarity": "COMMON",
    "image_url": null,
    "effects": [],
    "default_unlocked": true,
    "is_active": true,
    "collection_id": "dwarf",
    "visual_auras": [],
    "attack": 1,
    "defense": 5
  },
  {
    "id": "dwa_014_rompe_escudos_de_bronze",
    "name": "Rompe-Escudos de Bronze",
    "type": "DEFENDER",
    "race": "dwarf",
    "class": null,
    "cost": 4,
    "abilities": [
      "rush",
      "taunt"
    ],
    "text": "Ini. Prov",
    "rarity": "COMMON",
    "image_url": null,
    "effects": [],
    "default_unlocked": true,
    "is_active": true,
    "collection_id": "dwarf",
    "visual_auras": [],
    "attack": 4,
    "defense": 4
  },
  {
    "id": "dwa_015_general_de_muralha_de_escudos",
    "name": "General de Muralha de Escudos",
    "type": "DEFENDER",
    "race": "dwarf",
    "class": null,
    "cost": 6,
    "abilities": [
      "taunt"
    ],
    "text": "Prov",
    "rarity": "COMMON",
    "image_url": null,
    "effects": [],
    "default_unlocked": true,
    "is_active": true,
    "collection_id": "dwarf",
    "visual_auras": [],
    "attack": 3,
    "defense": 8
  },
  {
    "id": "dwa_016_minerador_de_mithril",
    "name": "Minerador de Mithril",
    "type": "DEFENDER",
    "race": "dwarf",
    "class": null,
    "cost": 2,
    "abilities": [],
    "text": "—",
    "rarity": "COMMON",
    "image_url": null,
    "effects": [],
    "default_unlocked": true,
    "is_active": true,
    "collection_id": "dwarf",
    "visual_auras": [],
    "attack": 1,
    "defense": 4
  },
  {
    "id": "dwa_017_mestre_da_catapulta",
    "name": "Mestre da Catapulta",
    "type": "DEFENDER",
    "race": "dwarf",
    "class": null,
    "cost": 5,
    "abilities": [
      "rush"
    ],
    "text": "Ini. 3 dmg",
    "rarity": "COMMON",
    "image_url": null,
    "effects": [],
    "default_unlocked": true,
    "is_active": true,
    "collection_id": "dwarf",
    "visual_auras": [],
    "attack": 2,
    "defense": 5
  },
  {
    "id": "dwa_018_veterano_da_grande_guerra",
    "name": "Veterano da Grande Guerra",
    "type": "DEFENDER",
    "race": "dwarf",
    "class": null,
    "cost": 7,
    "abilities": [
      "taunt"
    ],
    "text": "Prov",
    "rarity": "COMMON",
    "image_url": null,
    "effects": [],
    "default_unlocked": true,
    "is_active": true,
    "collection_id": "dwarf",
    "visual_auras": [],
    "attack": 5,
    "defense": 9
  },
  {
    "id": "dwa_019_guardiao_da_runa_de_sangue",
    "name": "Guardião da Runa de Sangue",
    "type": "DEFENDER",
    "race": "dwarf",
    "class": null,
    "cost": 4,
    "abilities": [],
    "text": "—",
    "rarity": "COMMON",
    "image_url": null,
    "effects": [],
    "default_unlocked": true,
    "is_active": true,
    "collection_id": "dwarf",
    "visual_auras": [],
    "attack": 3,
    "defense": 5
  },
  {
    "id": "dwa_020_o_colosso_de_pedra_ativado",
    "name": "O Colosso de Pedra Ativado",
    "type": "DEFENDER",
    "race": "dwarf",
    "class": null,
    "cost": 10,
    "abilities": [
      "taunt"
    ],
    "text": "Prov",
    "rarity": "COMMON",
    "image_url": null,
    "effects": [],
    "default_unlocked": true,
    "is_active": true,
    "collection_id": "dwarf",
    "visual_auras": [],
    "attack": 8,
    "defense": 15
  },
  {
    "id": "dwa_021_guardas_da_patrulha_de_pedra",
    "name": "Guardas da Patrulha de Pedra",
    "type": "DEFENDER",
    "race": "dwarf",
    "class": null,
    "cost": 1,
    "abilities": [],
    "text": "—",
    "rarity": "COMMON",
    "image_url": null,
    "effects": [],
    "default_unlocked": true,
    "is_active": true,
    "collection_id": "dwarf",
    "visual_auras": [],
    "attack": 1,
    "defense": 4
  },
  {
    "id": "dwa_022_mineiro_de_ferro_de_khund",
    "name": "Mineiro de Ferro de Khund",
    "type": "DEFENDER",
    "race": "dwarf",
    "class": null,
    "cost": 1,
    "abilities": [],
    "text": "—",
    "rarity": "COMMON",
    "image_url": null,
    "effects": [],
    "default_unlocked": true,
    "is_active": true,
    "collection_id": "dwarf",
    "visual_auras": [],
    "attack": 2,
    "defense": 2
  },
  {
    "id": "dwa_023_defensor_de_tunel_de_baixo",
    "name": "Defensor de Tunel de Baixo",
    "type": "DEFENDER",
    "race": "dwarf",
    "class": null,
    "cost": 2,
    "abilities": [],
    "text": "—",
    "rarity": "COMMON",
    "image_url": null,
    "effects": [],
    "default_unlocked": true,
    "is_active": true,
    "collection_id": "dwarf",
    "visual_auras": [],
    "attack": 1,
    "defense": 5
  },
  {
    "id": "dwa_024_batedor_de_planalto",
    "name": "Batedor de Planalto",
    "type": "DEFENDER",
    "race": "dwarf",
    "class": null,
    "cost": 2,
    "abilities": [],
    "text": "—",
    "rarity": "COMMON",
    "image_url": null,
    "effects": [],
    "default_unlocked": true,
    "is_active": true,
    "collection_id": "dwarf",
    "visual_auras": [],
    "attack": 3,
    "defense": 2
  },
  {
    "id": "dwa_025_guerreiro_do_cla_do_martelo",
    "name": "Guerreiro do Clã do Martelo",
    "type": "DEFENDER",
    "race": "dwarf",
    "class": null,
    "cost": 3,
    "abilities": [],
    "text": "—",
    "rarity": "COMMON",
    "image_url": null,
    "effects": [],
    "default_unlocked": true,
    "is_active": true,
    "collection_id": "dwarf",
    "visual_auras": [],
    "attack": 3,
    "defense": 5
  },
  {
    "id": "dwa_026_sentinela_de_quartzo",
    "name": "Sentinela de Quartzo",
    "type": "DEFENDER",
    "race": "dwarf",
    "class": null,
    "cost": 3,
    "abilities": [],
    "text": "—",
    "rarity": "COMMON",
    "image_url": null,
    "effects": [],
    "default_unlocked": true,
    "is_active": true,
    "collection_id": "dwarf",
    "visual_auras": [],
    "attack": 2,
    "defense": 6
  },
  {
    "id": "dwa_027_infantaria_de_ferro_pesado",
    "name": "Infantaria de Ferro Pesado",
    "type": "DEFENDER",
    "race": "dwarf",
    "class": null,
    "cost": 4,
    "abilities": [],
    "text": "—",
    "rarity": "COMMON",
    "image_url": null,
    "effects": [],
    "default_unlocked": true,
    "is_active": true,
    "collection_id": "dwarf",
    "visual_auras": [],
    "attack": 4,
    "defense": 6
  },
  {
    "id": "dwa_028_protetor_de_arcas_douradas",
    "name": "Protetor de Arcas Douradas",
    "type": "DEFENDER",
    "race": "dwarf",
    "class": null,
    "cost": 4,
    "abilities": [],
    "text": "—",
    "rarity": "COMMON",
    "image_url": null,
    "effects": [],
    "default_unlocked": true,
    "is_active": true,
    "collection_id": "dwarf",
    "visual_auras": [],
    "attack": 3,
    "defense": 7
  },
  {
    "id": "dwa_029_mestre_de_armas_de_obsidian",
    "name": "Mestre de Armas de Obsidian",
    "type": "DEFENDER",
    "race": "dwarf",
    "class": null,
    "cost": 5,
    "abilities": [],
    "text": "—",
    "rarity": "COMMON",
    "image_url": null,
    "effects": [],
    "default_unlocked": true,
    "is_active": true,
    "collection_id": "dwarf",
    "visual_auras": [],
    "attack": 5,
    "defense": 6
  },
  {
    "id": "dwa_030_veterano_do_salao_de_bronze",
    "name": "Veterano do Salão de Bronze",
    "type": "DEFENDER",
    "race": "dwarf",
    "class": null,
    "cost": 5,
    "abilities": [],
    "text": "—",
    "rarity": "COMMON",
    "image_url": null,
    "effects": [],
    "default_unlocked": true,
    "is_active": true,
    "collection_id": "dwarf",
    "visual_auras": [],
    "attack": 4,
    "defense": 8
  },
  {
    "id": "dwa_031_forjado_em_granito",
    "name": "Forjado em Granito",
    "type": "DEFENDER",
    "race": "dwarf",
    "class": null,
    "cost": 6,
    "abilities": [],
    "text": "—",
    "rarity": "COMMON",
    "image_url": null,
    "effects": [],
    "default_unlocked": true,
    "is_active": true,
    "collection_id": "dwarf",
    "visual_auras": [],
    "attack": 5,
    "defense": 9
  },
  {
    "id": "dwa_032_escudeiro_de_prata",
    "name": "Escudeiro de Prata",
    "type": "DEFENDER",
    "race": "dwarf",
    "class": null,
    "cost": 0,
    "abilities": [],
    "text": "—",
    "rarity": "COMMON",
    "image_url": null,
    "effects": [],
    "default_unlocked": true,
    "is_active": true,
    "collection_id": "dwarf",
    "visual_auras": [],
    "attack": 0,
    "defense": 3
  },
  {
    "id": "dwa_033_vigia_das_pontes_de_pedra",
    "name": "Vigia das Pontes de Pedra",
    "type": "DEFENDER",
    "race": "dwarf",
    "class": null,
    "cost": 2,
    "abilities": [],
    "text": "—",
    "rarity": "COMMON",
    "image_url": null,
    "effects": [],
    "default_unlocked": true,
    "is_active": true,
    "collection_id": "dwarf",
    "visual_auras": [],
    "attack": 2,
    "defense": 4
  },
  {
    "id": "dwa_034_batedor_das_cavernas",
    "name": "Batedor das Cavernas",
    "type": "DEFENDER",
    "race": "dwarf",
    "class": null,
    "cost": 1,
    "abilities": [],
    "text": "—",
    "rarity": "COMMON",
    "image_url": null,
    "effects": [],
    "default_unlocked": true,
    "is_active": true,
    "collection_id": "dwarf",
    "visual_auras": [],
    "attack": 2,
    "defense": 1
  },
  {
    "id": "dwa_035_guardiao_do_altar_de_ouro",
    "name": "Guardião do Altar de Ouro",
    "type": "DEFENDER",
    "race": "dwarf",
    "class": null,
    "cost": 6,
    "abilities": [],
    "text": "—",
    "rarity": "COMMON",
    "image_url": null,
    "effects": [],
    "default_unlocked": true,
    "is_active": true,
    "collection_id": "dwarf",
    "visual_auras": [],
    "attack": 6,
    "defense": 7
  },
  {
    "id": "dwa_036_runa_de_protecao_absoluta",
    "name": "Runa de Proteção Absoluta",
    "type": "ABILITY",
    "race": null,
    "class": null,
    "cost": 2,
    "abilities": [
      "taunt"
    ],
    "text": "Prov",
    "rarity": "COMMON",
    "image_url": null,
    "effects": [],
    "default_unlocked": true,
    "is_active": true,
    "collection_id": "dwarf",
    "visual_auras": [],
    "attack": null,
    "defense": null
  },
  {
    "id": "dwa_037_colapso_da_caverna",
    "name": "Colapso da Caverna",
    "type": "ABILITY",
    "race": null,
    "class": null,
    "cost": 5,
    "abilities": [],
    "text": "—",
    "rarity": "COMMON",
    "image_url": null,
    "effects": [],
    "default_unlocked": true,
    "is_active": true,
    "collection_id": "dwarf",
    "visual_auras": [],
    "attack": null,
    "defense": null
  },
  {
    "id": "dwa_038_bencao_do_ancestral",
    "name": "Benção do Ancestral",
    "type": "ABILITY",
    "race": null,
    "class": null,
    "cost": 3,
    "abilities": [],
    "text": "Cura 5",
    "rarity": "COMMON",
    "image_url": null,
    "effects": [
      {
        "type": "DRAW",
        "value": 1,
        "target": "OWN_GENERAL",
        "trigger": "INSTANT",
        "duration": 0
      }
    ],
    "default_unlocked": true,
    "is_active": true,
    "collection_id": "dwarf",
    "visual_auras": [],
    "attack": null,
    "defense": null
  },
  {
    "id": "dwa_039_fogo_da_forja",
    "name": "Fogo da Forja",
    "type": "ABILITY",
    "race": null,
    "class": null,
    "cost": 2,
    "abilities": [],
    "text": "3 dmg",
    "rarity": "COMMON",
    "image_url": null,
    "effects": [
      {
        "type": "DAMAGE",
        "value": 3,
        "target": "ENEMY_GENERAL",
        "trigger": "INSTANT",
        "duration": 0
      }
    ],
    "default_unlocked": true,
    "is_active": true,
    "collection_id": "dwarf",
    "visual_auras": [],
    "attack": null,
    "defense": null
  },
  {
    "id": "dwa_040_armadura_runica_de_emergencia",
    "name": "Armadura Rúnica de Emergência",
    "type": "ABILITY",
    "race": null,
    "class": null,
    "cost": 1,
    "abilities": [],
    "text": "—",
    "rarity": "COMMON",
    "image_url": null,
    "effects": [],
    "default_unlocked": true,
    "is_active": true,
    "collection_id": "dwarf",
    "visual_auras": [],
    "attack": null,
    "defense": null
  },
  {
    "id": "dwa_041_ganancia_de_ouro",
    "name": "Ganância de Ouro",
    "type": "ABILITY",
    "race": null,
    "class": null,
    "cost": 4,
    "abilities": [],
    "text": "+3 card",
    "rarity": "COMMON",
    "image_url": null,
    "effects": [
      {
        "type": "DRAW",
        "value": 3,
        "target": "OWN_GENERAL",
        "trigger": "INSTANT",
        "duration": 0
      }
    ],
    "default_unlocked": true,
    "is_active": true,
    "collection_id": "dwarf",
    "visual_auras": [],
    "attack": null,
    "defense": null
  },
  {
    "id": "dwa_042_terremoto_controlado",
    "name": "Terremoto Controlado",
    "type": "ABILITY",
    "race": null,
    "class": null,
    "cost": 6,
    "abilities": [],
    "text": "—",
    "rarity": "COMMON",
    "image_url": null,
    "effects": [],
    "default_unlocked": true,
    "is_active": true,
    "collection_id": "dwarf",
    "visual_auras": [],
    "attack": null,
    "defense": null
  },
  {
    "id": "dwa_043_retorno_as_montanhas",
    "name": "Retorno às Montanhas",
    "type": "ABILITY",
    "race": null,
    "class": null,
    "cost": 2,
    "abilities": [],
    "text": "Cura 10",
    "rarity": "COMMON",
    "image_url": null,
    "effects": [],
    "default_unlocked": true,
    "is_active": true,
    "collection_id": "dwarf",
    "visual_auras": [],
    "attack": null,
    "defense": null
  },
  {
    "id": "dwa_044_sabotagem_de_equipamento",
    "name": "Sabotagem de Equipamento",
    "type": "ABILITY",
    "race": null,
    "class": null,
    "cost": 3,
    "abilities": [],
    "text": "—",
    "rarity": "COMMON",
    "image_url": null,
    "effects": [],
    "default_unlocked": true,
    "is_active": true,
    "collection_id": "dwarf",
    "visual_auras": [],
    "attack": null,
    "defense": null
  },
  {
    "id": "dwa_045_muralha_de_gelo_e_pedra",
    "name": "Muralha de Gelo e Pedra",
    "type": "ABILITY",
    "race": null,
    "class": null,
    "cost": 4,
    "abilities": [],
    "text": "—",
    "rarity": "COMMON",
    "image_url": null,
    "effects": [],
    "default_unlocked": true,
    "is_active": true,
    "collection_id": "dwarf",
    "visual_auras": [],
    "attack": null,
    "defense": null
  },
  {
    "id": "dwa_046_chamado_das_profundezas",
    "name": "Chamado das Profundezas",
    "type": "ABILITY",
    "race": null,
    "class": null,
    "cost": 3,
    "abilities": [],
    "text": "—",
    "rarity": "COMMON",
    "image_url": null,
    "effects": [],
    "default_unlocked": true,
    "is_active": true,
    "collection_id": "dwarf",
    "visual_auras": [],
    "attack": null,
    "defense": null
  },
  {
    "id": "dwa_047_disciplina_de_ferro",
    "name": "Disciplina de Ferro",
    "type": "ABILITY",
    "race": null,
    "class": null,
    "cost": 2,
    "abilities": [],
    "text": "—",
    "rarity": "COMMON",
    "image_url": null,
    "effects": [],
    "default_unlocked": true,
    "is_active": true,
    "collection_id": "dwarf",
    "visual_auras": [],
    "attack": null,
    "defense": null
  },
  {
    "id": "dwa_048_armadilha_de_fosso",
    "name": "Armadilha de Fosso",
    "type": "ABILITY",
    "race": null,
    "class": null,
    "cost": 1,
    "abilities": [],
    "text": "—",
    "rarity": "COMMON",
    "image_url": null,
    "effects": [],
    "default_unlocked": true,
    "is_active": true,
    "collection_id": "dwarf",
    "visual_auras": [],
    "attack": null,
    "defense": null
  },
  {
    "id": "dwa_049_reparos_rapidos",
    "name": "Reparos Rápidos",
    "type": "ABILITY",
    "race": null,
    "class": null,
    "cost": 0,
    "abilities": [],
    "text": "Cura 2",
    "rarity": "COMMON",
    "image_url": null,
    "effects": [],
    "default_unlocked": true,
    "is_active": true,
    "collection_id": "dwarf",
    "visual_auras": [],
    "attack": null,
    "defense": null
  },
  {
    "id": "dwa_050_vontade_indomavel",
    "name": "Vontade Indomável",
    "type": "ABILITY",
    "race": null,
    "class": null,
    "cost": 5,
    "abilities": [],
    "text": "—",
    "rarity": "COMMON",
    "image_url": null,
    "effects": [],
    "default_unlocked": true,
    "is_active": true,
    "collection_id": "dwarf",
    "visual_auras": [],
    "attack": null,
    "defense": null
  },
  {
    "id": "dwa_051_eco_das_cavernas",
    "name": "Eco das Cavernas",
    "type": "ABILITY",
    "race": null,
    "class": null,
    "cost": 3,
    "abilities": [],
    "text": "—",
    "rarity": "COMMON",
    "image_url": null,
    "effects": [],
    "default_unlocked": true,
    "is_active": true,
    "collection_id": "dwarf",
    "visual_auras": [],
    "attack": null,
    "defense": null
  },
  {
    "id": "dwa_052_escudo_de_mana",
    "name": "Escudo de Mana",
    "type": "ABILITY",
    "race": null,
    "class": null,
    "cost": 4,
    "abilities": [],
    "text": "—",
    "rarity": "COMMON",
    "image_url": null,
    "effects": [],
    "default_unlocked": true,
    "is_active": true,
    "collection_id": "dwarf",
    "visual_auras": [],
    "attack": null,
    "defense": null
  },
  {
    "id": "dwa_053_julgamento_do_martelo",
    "name": "Julgamento do Martelo",
    "type": "ABILITY",
    "race": null,
    "class": null,
    "cost": 7,
    "abilities": [],
    "text": "—",
    "rarity": "COMMON",
    "image_url": null,
    "effects": [],
    "default_unlocked": true,
    "is_active": true,
    "collection_id": "dwarf",
    "visual_auras": [],
    "attack": null,
    "defense": null
  },
  {
    "id": "dwa_054_fortificacao_subita",
    "name": "Fortificação Súbita",
    "type": "ABILITY",
    "race": null,
    "class": null,
    "cost": 3,
    "abilities": [
      "taunt"
    ],
    "text": "Prov",
    "rarity": "COMMON",
    "image_url": null,
    "effects": [],
    "default_unlocked": true,
    "is_active": true,
    "collection_id": "dwarf",
    "visual_auras": [],
    "attack": null,
    "defense": null
  },
  {
    "id": "dwa_055_legado_de_pedra",
    "name": "Legado de Pedra",
    "type": "ABILITY",
    "race": null,
    "class": null,
    "cost": 8,
    "abilities": [],
    "text": "—",
    "rarity": "COMMON",
    "image_url": null,
    "effects": [],
    "default_unlocked": true,
    "is_active": true,
    "collection_id": "dwarf",
    "visual_auras": [],
    "attack": null,
    "defense": null
  },
  {
    "id": "dwa_056_martelo_do_comandante",
    "name": "Martelo do Comandante",
    "type": "EQUIPMENT",
    "race": null,
    "class": null,
    "cost": 3,
    "abilities": [],
    "text": "—",
    "rarity": "COMMON",
    "image_url": null,
    "effects": [],
    "default_unlocked": true,
    "is_active": true,
    "collection_id": "dwarf",
    "visual_auras": [],
    "attack": null,
    "defense": null
  },
  {
    "id": "dwa_057_escudo_torre_de_ferro_negro",
    "name": "Escudo Torre de Ferro Negro",
    "type": "EQUIPMENT",
    "race": null,
    "class": null,
    "cost": 4,
    "abilities": [
      "taunt"
    ],
    "text": "Prov",
    "rarity": "COMMON",
    "image_url": null,
    "effects": [],
    "default_unlocked": true,
    "is_active": true,
    "collection_id": "dwarf",
    "visual_auras": [],
    "attack": null,
    "defense": null
  },
  {
    "id": "dwa_058_elmo_da_visao_runica",
    "name": "Elmo da Visão Rúnica",
    "type": "EQUIPMENT",
    "race": null,
    "class": null,
    "cost": 2,
    "abilities": [],
    "text": "—",
    "rarity": "COMMON",
    "image_url": null,
    "effects": [],
    "default_unlocked": true,
    "is_active": true,
    "collection_id": "dwarf",
    "visual_auras": [],
    "attack": null,
    "defense": null
  },
  {
    "id": "dwa_059_machado_de_batalha_do_rei",
    "name": "Machado de Batalha do Rei",
    "type": "EQUIPMENT",
    "race": null,
    "class": null,
    "cost": 6,
    "abilities": [],
    "text": "2 dmg",
    "rarity": "COMMON",
    "image_url": null,
    "effects": [],
    "default_unlocked": true,
    "is_active": true,
    "collection_id": "dwarf",
    "visual_auras": [],
    "attack": null,
    "defense": null
  },
  {
    "id": "dwa_060_peitoral_de_mithril",
    "name": "Peitoral de Mithril",
    "type": "EQUIPMENT",
    "race": null,
    "class": null,
    "cost": 5,
    "abilities": [],
    "text": "—",
    "rarity": "COMMON",
    "image_url": null,
    "effects": [],
    "default_unlocked": true,
    "is_active": true,
    "collection_id": "dwarf",
    "visual_auras": [],
    "attack": null,
    "defense": null
  },
  {
    "id": "dwa_061_luvas_do_forjador",
    "name": "Luvas do Forjador",
    "type": "EQUIPMENT",
    "race": null,
    "class": null,
    "cost": 2,
    "abilities": [],
    "text": "—",
    "rarity": "COMMON",
    "image_url": null,
    "effects": [],
    "default_unlocked": true,
    "is_active": true,
    "collection_id": "dwarf",
    "visual_auras": [],
    "attack": null,
    "defense": null
  },
  {
    "id": "dwa_062_runa_de_gelo_eterno",
    "name": "Runa de Gelo Eterno",
    "type": "EQUIPMENT",
    "race": null,
    "class": null,
    "cost": 3,
    "abilities": [],
    "text": "—",
    "rarity": "COMMON",
    "image_url": null,
    "effects": [],
    "default_unlocked": true,
    "is_active": true,
    "collection_id": "dwarf",
    "visual_auras": [],
    "attack": null,
    "defense": null
  },
  {
    "id": "dwa_063_botas_de_chumbo",
    "name": "Botas de Chumbo",
    "type": "EQUIPMENT",
    "race": null,
    "class": null,
    "cost": 1,
    "abilities": [],
    "text": "—",
    "rarity": "COMMON",
    "image_url": null,
    "effects": [],
    "default_unlocked": true,
    "is_active": true,
    "collection_id": "dwarf",
    "visual_auras": [],
    "attack": null,
    "defense": null
  },
  {
    "id": "dwa_064_picareta_de_diamante",
    "name": "Picareta de Diamante",
    "type": "EQUIPMENT",
    "race": null,
    "class": null,
    "cost": 2,
    "abilities": [],
    "text": "+2 card",
    "rarity": "COMMON",
    "image_url": null,
    "effects": [],
    "default_unlocked": true,
    "is_active": true,
    "collection_id": "dwarf",
    "visual_auras": [],
    "attack": null,
    "defense": null
  },
  {
    "id": "dwa_065_capa_de_pedra_camuflada",
    "name": "Capa de Pedra Camuflada",
    "type": "EQUIPMENT",
    "race": null,
    "class": null,
    "cost": 3,
    "abilities": [
      "taunt"
    ],
    "text": "Prov",
    "rarity": "COMMON",
    "image_url": null,
    "effects": [],
    "default_unlocked": true,
    "is_active": true,
    "collection_id": "dwarf",
    "visual_auras": [],
    "attack": null,
    "defense": null
  },
  {
    "id": "dwa_066_escudo_de_bronze_ancestral",
    "name": "Escudo de Bronze Ancestral",
    "type": "EQUIPMENT",
    "race": null,
    "class": null,
    "cost": 2,
    "abilities": [],
    "text": "—",
    "rarity": "COMMON",
    "image_url": null,
    "effects": [],
    "default_unlocked": true,
    "is_active": true,
    "collection_id": "dwarf",
    "visual_auras": [],
    "attack": null,
    "defense": null
  },
  {
    "id": "dwa_067_martelo_de_arremesso_runico",
    "name": "Martelo de Arremesso Rúnico",
    "type": "EQUIPMENT",
    "race": null,
    "class": null,
    "cost": 4,
    "abilities": [
      "taunt"
    ],
    "text": "Prov",
    "rarity": "COMMON",
    "image_url": null,
    "effects": [],
    "default_unlocked": true,
    "is_active": true,
    "collection_id": "dwarf",
    "visual_auras": [],
    "attack": null,
    "defense": null
  },
  {
    "id": "dwa_068_cinto_de_forca_do_gigante",
    "name": "Cinto de Força do Gigante",
    "type": "EQUIPMENT",
    "race": null,
    "class": null,
    "cost": 5,
    "abilities": [],
    "text": "—",
    "rarity": "COMMON",
    "image_url": null,
    "effects": [],
    "default_unlocked": true,
    "is_active": true,
    "collection_id": "dwarf",
    "visual_auras": [],
    "attack": null,
    "defense": null
  },
  {
    "id": "dwa_069_tocha_de_fogo_eterno",
    "name": "Tocha de Fogo Eterno",
    "type": "EQUIPMENT",
    "race": null,
    "class": null,
    "cost": 1,
    "abilities": [],
    "text": "1 dmg",
    "rarity": "COMMON",
    "image_url": null,
    "effects": [],
    "default_unlocked": true,
    "is_active": true,
    "collection_id": "dwarf",
    "visual_auras": [],
    "attack": null,
    "defense": null
  },
  {
    "id": "dwa_070_a_coroa_de_khazad_gund",
    "name": "A Coroa de Khazad-Gund",
    "type": "EQUIPMENT",
    "race": null,
    "class": null,
    "cost": 7,
    "abilities": [],
    "text": "—",
    "rarity": "COMMON",
    "image_url": null,
    "effects": [],
    "default_unlocked": true,
    "is_active": true,
    "collection_id": "dwarf",
    "visual_auras": [],
    "attack": null,
    "defense": null
  }
] as unknown as Card[];
