import type { Card } from '../../../shared/types';

export const ELF_COLLECTION = {
  id: 'elf',
  name: 'Elfos',
  description: 'Fluxo Eterno — Elfos'
};

export const ELF_CARD_CATALOG = [
  {
    "id": "elf_001_aprendiz_do_fluxo",
    "name": "Aprendiz do Fluxo",
    "type": "DEFENDER",
    "race": "elf",
    "class": null,
    "cost": 1,
    "abilities": [
      "rush"
    ],
    "text": "Ini",
    "rarity": "COMMON",
    "image_url": null,
    "effects": [],
    "default_unlocked": true,
    "is_active": true,
    "collection_id": "elf",
    "visual_auras": [],
    "attack": 1,
    "defense": 2
  },
  {
    "id": "elf_002_guardiao_da_raiz_viva",
    "name": "Guardião da Raiz Viva",
    "type": "DEFENDER",
    "race": "elf",
    "class": null,
    "cost": 3,
    "abilities": [
      "taunt"
    ],
    "text": "Prov",
    "rarity": "COMMON",
    "image_url": null,
    "effects": [],
    "default_unlocked": true,
    "is_active": true,
    "collection_id": "elf",
    "visual_auras": [],
    "attack": 2,
    "defense": 4
  },
  {
    "id": "elf_003_tecela_de_cipos_elfica",
    "name": "Tecelã de Cipós Élfica",
    "type": "DEFENDER",
    "race": "elf",
    "class": null,
    "cost": 2,
    "abilities": [
      "taunt"
    ],
    "text": "Prov",
    "rarity": "COMMON",
    "image_url": null,
    "effects": [],
    "default_unlocked": true,
    "is_active": true,
    "collection_id": "elf",
    "visual_auras": [],
    "attack": 2,
    "defense": 2
  },
  {
    "id": "elf_004_sentinela_do_eco",
    "name": "Sentinela do Eco",
    "type": "DEFENDER",
    "race": "elf",
    "class": null,
    "cost": 4,
    "abilities": [],
    "text": "—",
    "rarity": "COMMON",
    "image_url": null,
    "effects": [],
    "default_unlocked": true,
    "is_active": true,
    "collection_id": "elf",
    "visual_auras": [],
    "attack": 3,
    "defense": 3
  },
  {
    "id": "elf_005_druida_da_floresta_profunda",
    "name": "Druida da Floresta Profunda",
    "type": "DEFENDER",
    "race": "elf",
    "class": null,
    "cost": 5,
    "abilities": [],
    "text": "Cura 2",
    "rarity": "COMMON",
    "image_url": null,
    "effects": [],
    "default_unlocked": true,
    "is_active": true,
    "collection_id": "elf",
    "visual_auras": [],
    "attack": 4,
    "defense": 5
  },
  {
    "id": "elf_006_mestre_de_armas_silvestre",
    "name": "Mestre de Armas Silvestre",
    "type": "DEFENDER",
    "race": "elf",
    "class": null,
    "cost": 4,
    "abilities": [
      "rush"
    ],
    "text": "Ini",
    "rarity": "COMMON",
    "image_url": null,
    "effects": [],
    "default_unlocked": true,
    "is_active": true,
    "collection_id": "elf",
    "visual_auras": [],
    "attack": 4,
    "defense": 4
  },
  {
    "id": "elf_007_arauto_da_alvorada_elfica",
    "name": "Arauto da Alvorada Élfica",
    "type": "DEFENDER",
    "race": "elf",
    "class": null,
    "cost": 3,
    "abilities": [
      "rush"
    ],
    "text": "Ini",
    "rarity": "COMMON",
    "image_url": null,
    "effects": [],
    "default_unlocked": true,
    "is_active": true,
    "collection_id": "elf",
    "visual_auras": [],
    "attack": 2,
    "defense": 3
  },
  {
    "id": "elf_008_sabio_do_orvalho_lunar",
    "name": "Sábio do Orvalho Lunar",
    "type": "DEFENDER",
    "race": "elf",
    "class": null,
    "cost": 2,
    "abilities": [],
    "text": "—",
    "rarity": "COMMON",
    "image_url": null,
    "effects": [],
    "default_unlocked": true,
    "is_active": true,
    "collection_id": "elf",
    "visual_auras": [],
    "attack": 1,
    "defense": 3
  },
  {
    "id": "elf_009_vingador_das_sombras_verdes",
    "name": "Vingador das Sombras Verdes",
    "type": "DEFENDER",
    "race": "elf",
    "class": null,
    "cost": 6,
    "abilities": [
      "rush"
    ],
    "text": "Ini",
    "rarity": "COMMON",
    "image_url": null,
    "effects": [],
    "default_unlocked": true,
    "is_active": true,
    "collection_id": "elf",
    "visual_auras": [],
    "attack": 6,
    "defense": 4
  },
  {
    "id": "elf_010_matriarca_do_bosque",
    "name": "Matriarca do Bosque",
    "type": "DEFENDER",
    "race": "elf",
    "class": null,
    "cost": 8,
    "abilities": [
      "taunt"
    ],
    "text": "Prov",
    "rarity": "COMMON",
    "image_url": null,
    "effects": [],
    "default_unlocked": true,
    "is_active": true,
    "collection_id": "elf",
    "visual_auras": [],
    "attack": 5,
    "defense": 8
  },
  {
    "id": "elf_011_espreitador_de_vendaval",
    "name": "Espreitador de Vendaval",
    "type": "DEFENDER",
    "race": "elf",
    "class": null,
    "cost": 3,
    "abilities": [],
    "text": "—",
    "rarity": "COMMON",
    "image_url": null,
    "effects": [],
    "default_unlocked": true,
    "is_active": true,
    "collection_id": "elf",
    "visual_auras": [],
    "attack": 3,
    "defense": 2
  },
  {
    "id": "elf_012_canalizadora_de_mana_silvestre",
    "name": "Canalizadora de Mana Silvestre",
    "type": "DEFENDER",
    "race": "elf",
    "class": null,
    "cost": 2,
    "abilities": [],
    "text": "—",
    "rarity": "COMMON",
    "image_url": null,
    "effects": [],
    "default_unlocked": true,
    "is_active": true,
    "collection_id": "elf",
    "visual_auras": [],
    "attack": 1,
    "defense": 4
  },
  {
    "id": "elf_013_capitao_da_guarda_das_folhas",
    "name": "Capitão da Guarda das Folhas",
    "type": "DEFENDER",
    "race": "elf",
    "class": null,
    "cost": 5,
    "abilities": [
      "rush"
    ],
    "text": "Ini",
    "rarity": "COMMON",
    "image_url": null,
    "effects": [],
    "default_unlocked": true,
    "is_active": true,
    "collection_id": "elf",
    "visual_auras": [],
    "attack": 4,
    "defense": 6
  },
  {
    "id": "elf_014_dancarina_das_laminas_de_vento",
    "name": "Dançarina das Lâminas de Vento",
    "type": "DEFENDER",
    "race": "elf",
    "class": null,
    "cost": 4,
    "abilities": [],
    "text": "2 dmg",
    "rarity": "COMMON",
    "image_url": null,
    "effects": [],
    "default_unlocked": true,
    "is_active": true,
    "collection_id": "elf",
    "visual_auras": [],
    "attack": 3,
    "defense": 5
  },
  {
    "id": "elf_015_sumo_sacerdote_do_carvalho",
    "name": "Sumo Sacerdote do Carvalho",
    "type": "DEFENDER",
    "race": "elf",
    "class": null,
    "cost": 7,
    "abilities": [],
    "text": "—",
    "rarity": "COMMON",
    "image_url": null,
    "effects": [],
    "default_unlocked": true,
    "is_active": true,
    "collection_id": "elf",
    "visual_auras": [],
    "attack": 5,
    "defense": 5
  },
  {
    "id": "elf_016_arqueiro_de_precisao_estelar",
    "name": "Arqueiro de Precisão Estelar",
    "type": "DEFENDER",
    "race": "elf",
    "class": null,
    "cost": 3,
    "abilities": [
      "taunt"
    ],
    "text": "Prov. 2 dmg",
    "rarity": "COMMON",
    "image_url": null,
    "effects": [],
    "default_unlocked": true,
    "is_active": true,
    "collection_id": "elf",
    "visual_auras": [],
    "attack": 4,
    "defense": 2
  },
  {
    "id": "elf_017_guardiao_do_templo_das_sombras",
    "name": "Guardião do Templo das Sombras",
    "type": "DEFENDER",
    "race": "elf",
    "class": null,
    "cost": 6,
    "abilities": [
      "taunt"
    ],
    "text": "Prov. +2 card",
    "rarity": "COMMON",
    "image_url": null,
    "effects": [],
    "default_unlocked": true,
    "is_active": true,
    "collection_id": "elf",
    "visual_auras": [],
    "attack": 5,
    "defense": 7
  },
  {
    "id": "elf_018_invocador_de_enxames",
    "name": "Invocador de Enxames",
    "type": "DEFENDER",
    "race": "elf",
    "class": null,
    "cost": 4,
    "abilities": [
      "rush"
    ],
    "text": "Ini",
    "rarity": "COMMON",
    "image_url": null,
    "effects": [],
    "default_unlocked": true,
    "is_active": true,
    "collection_id": "elf",
    "visual_auras": [],
    "attack": 2,
    "defense": 2
  },
  {
    "id": "elf_019_andarilho_dos_reinos_esquecidos",
    "name": "Andarilho dos Reinos Esquecidos",
    "type": "DEFENDER",
    "race": "elf",
    "class": null,
    "cost": 2,
    "abilities": [],
    "text": "—",
    "rarity": "COMMON",
    "image_url": null,
    "effects": [],
    "default_unlocked": true,
    "is_active": true,
    "collection_id": "elf",
    "visual_auras": [],
    "attack": 2,
    "defense": 2
  },
  {
    "id": "elf_020_avatar_da_natureza_feroz",
    "name": "Avatar da Natureza Feroz",
    "type": "DEFENDER",
    "race": "elf",
    "class": null,
    "cost": 10,
    "abilities": [
      "rush",
      "taunt"
    ],
    "text": "Ini. Prov",
    "rarity": "COMMON",
    "image_url": null,
    "effects": [],
    "default_unlocked": true,
    "is_active": true,
    "collection_id": "elf",
    "visual_auras": [],
    "attack": 10,
    "defense": 10
  },
  {
    "id": "elf_021_recruta_de_folha_prata",
    "name": "Recruta de Folha-Prata",
    "type": "DEFENDER",
    "race": "elf",
    "class": null,
    "cost": 1,
    "abilities": [],
    "text": "—",
    "rarity": "COMMON",
    "image_url": null,
    "effects": [],
    "default_unlocked": true,
    "is_active": true,
    "collection_id": "elf",
    "visual_auras": [],
    "attack": 2,
    "defense": 1
  },
  {
    "id": "elf_022_sentinela_da_borda",
    "name": "Sentinela da Borda",
    "type": "DEFENDER",
    "race": "elf",
    "class": null,
    "cost": 2,
    "abilities": [],
    "text": "—",
    "rarity": "COMMON",
    "image_url": null,
    "effects": [],
    "default_unlocked": true,
    "is_active": true,
    "collection_id": "elf",
    "visual_auras": [],
    "attack": 2,
    "defense": 3
  },
  {
    "id": "elf_023_guerreiro_de_tronco_forte",
    "name": "Guerreiro de Tronco-Forte",
    "type": "DEFENDER",
    "race": "elf",
    "class": null,
    "cost": 3,
    "abilities": [],
    "text": "—",
    "rarity": "COMMON",
    "image_url": null,
    "effects": [],
    "default_unlocked": true,
    "is_active": true,
    "collection_id": "elf",
    "visual_auras": [],
    "attack": 3,
    "defense": 4
  },
  {
    "id": "elf_024_cacador_de_feras_elfico",
    "name": "Caçador de Feras Élfico",
    "type": "DEFENDER",
    "race": "elf",
    "class": null,
    "cost": 4,
    "abilities": [],
    "text": "—",
    "rarity": "COMMON",
    "image_url": null,
    "effects": [],
    "default_unlocked": true,
    "is_active": true,
    "collection_id": "elf",
    "visual_auras": [],
    "attack": 5,
    "defense": 4
  },
  {
    "id": "elf_025_veterano_da_guerra_verde",
    "name": "Veterano da Guerra Verde",
    "type": "DEFENDER",
    "race": "elf",
    "class": null,
    "cost": 5,
    "abilities": [],
    "text": "—",
    "rarity": "COMMON",
    "image_url": null,
    "effects": [],
    "default_unlocked": true,
    "is_active": true,
    "collection_id": "elf",
    "visual_auras": [],
    "attack": 5,
    "defense": 6
  },
  {
    "id": "elf_026_lanceiro_de_espinheiro",
    "name": "Lanceiro de Espinheiro",
    "type": "DEFENDER",
    "race": "elf",
    "class": null,
    "cost": 2,
    "abilities": [],
    "text": "—",
    "rarity": "COMMON",
    "image_url": null,
    "effects": [],
    "default_unlocked": true,
    "is_active": true,
    "collection_id": "elf",
    "visual_auras": [],
    "attack": 3,
    "defense": 2
  },
  {
    "id": "elf_027_defensor_do_dossel",
    "name": "Defensor do Dossel",
    "type": "DEFENDER",
    "race": "elf",
    "class": null,
    "cost": 3,
    "abilities": [],
    "text": "—",
    "rarity": "COMMON",
    "image_url": null,
    "effects": [],
    "default_unlocked": true,
    "is_active": true,
    "collection_id": "elf",
    "visual_auras": [],
    "attack": 1,
    "defense": 6
  },
  {
    "id": "elf_028_espadachim_do_vento_norte",
    "name": "Espadachim do Vento Norte",
    "type": "DEFENDER",
    "race": "elf",
    "class": null,
    "cost": 4,
    "abilities": [],
    "text": "—",
    "rarity": "COMMON",
    "image_url": null,
    "effects": [],
    "default_unlocked": true,
    "is_active": true,
    "collection_id": "elf",
    "visual_auras": [],
    "attack": 4,
    "defense": 5
  },
  {
    "id": "elf_029_batedor_de_planicie",
    "name": "Batedor de Planície",
    "type": "DEFENDER",
    "race": "elf",
    "class": null,
    "cost": 1,
    "abilities": [],
    "text": "—",
    "rarity": "COMMON",
    "image_url": null,
    "effects": [],
    "default_unlocked": true,
    "is_active": true,
    "collection_id": "elf",
    "visual_auras": [],
    "attack": 1,
    "defense": 3
  },
  {
    "id": "elf_030_elite_do_carvalho_real",
    "name": "Elite do Carvalho Real",
    "type": "DEFENDER",
    "race": "elf",
    "class": null,
    "cost": 6,
    "abilities": [],
    "text": "—",
    "rarity": "COMMON",
    "image_url": null,
    "effects": [],
    "default_unlocked": true,
    "is_active": true,
    "collection_id": "elf",
    "visual_auras": [],
    "attack": 6,
    "defense": 7
  },
  {
    "id": "elf_031_patrulheiro_silencioso",
    "name": "Patrulheiro Silencioso",
    "type": "DEFENDER",
    "race": "elf",
    "class": null,
    "cost": 2,
    "abilities": [],
    "text": "—",
    "rarity": "COMMON",
    "image_url": null,
    "effects": [],
    "default_unlocked": true,
    "is_active": true,
    "collection_id": "elf",
    "visual_auras": [],
    "attack": 3,
    "defense": 1
  },
  {
    "id": "elf_032_guardiao_das_fontes",
    "name": "Guardião das Fontes",
    "type": "DEFENDER",
    "race": "elf",
    "class": null,
    "cost": 3,
    "abilities": [],
    "text": "—",
    "rarity": "COMMON",
    "image_url": null,
    "effects": [],
    "default_unlocked": true,
    "is_active": true,
    "collection_id": "elf",
    "visual_auras": [],
    "attack": 2,
    "defense": 5
  },
  {
    "id": "elf_033_escultor_de_arvores",
    "name": "Escultor de Árvores",
    "type": "DEFENDER",
    "race": "elf",
    "class": null,
    "cost": 4,
    "abilities": [],
    "text": "—",
    "rarity": "COMMON",
    "image_url": null,
    "effects": [],
    "default_unlocked": true,
    "is_active": true,
    "collection_id": "elf",
    "visual_auras": [],
    "attack": 4,
    "defense": 4
  },
  {
    "id": "elf_034_mestre_de_caca",
    "name": "Mestre de Caça",
    "type": "DEFENDER",
    "race": "elf",
    "class": null,
    "cost": 5,
    "abilities": [],
    "text": "—",
    "rarity": "COMMON",
    "image_url": null,
    "effects": [],
    "default_unlocked": true,
    "is_active": true,
    "collection_id": "elf",
    "visual_auras": [],
    "attack": 6,
    "defense": 4
  },
  {
    "id": "elf_035_ancestral_desperto",
    "name": "Ancestral Desperto",
    "type": "DEFENDER",
    "race": "elf",
    "class": null,
    "cost": 7,
    "abilities": [],
    "text": "—",
    "rarity": "COMMON",
    "image_url": null,
    "effects": [],
    "default_unlocked": true,
    "is_active": true,
    "collection_id": "elf",
    "visual_auras": [],
    "attack": 8,
    "defense": 8
  },
  {
    "id": "elf_036_bencao_de_gaia",
    "name": "Bênção de Gaia",
    "type": "ABILITY",
    "race": null,
    "class": null,
    "cost": 2,
    "abilities": [
      "rush"
    ],
    "text": "Ini",
    "rarity": "COMMON",
    "image_url": null,
    "effects": [],
    "default_unlocked": true,
    "is_active": true,
    "collection_id": "elf",
    "visual_auras": [],
    "attack": null,
    "defense": null
  },
  {
    "id": "elf_037_raizes_aprisionadoras",
    "name": "Raízes Aprisionadoras",
    "type": "ABILITY",
    "race": null,
    "class": null,
    "cost": 3,
    "abilities": [],
    "text": "—",
    "rarity": "COMMON",
    "image_url": null,
    "effects": [],
    "default_unlocked": true,
    "is_active": true,
    "collection_id": "elf",
    "visual_auras": [],
    "attack": null,
    "defense": null
  },
  {
    "id": "elf_038_vento_de_repulsao",
    "name": "Vento de Repulsão",
    "type": "ABILITY",
    "race": null,
    "class": null,
    "cost": 1,
    "abilities": [],
    "text": "—",
    "rarity": "COMMON",
    "image_url": null,
    "effects": [],
    "default_unlocked": true,
    "is_active": true,
    "collection_id": "elf",
    "visual_auras": [],
    "attack": null,
    "defense": null
  },
  {
    "id": "elf_039_chamado_da_matilha_elfica",
    "name": "Chamado da Matilha Élfica",
    "type": "ABILITY",
    "race": null,
    "class": null,
    "cost": 4,
    "abilities": [
      "rush"
    ],
    "text": "Ini",
    "rarity": "COMMON",
    "image_url": null,
    "effects": [],
    "default_unlocked": true,
    "is_active": true,
    "collection_id": "elf",
    "visual_auras": [],
    "attack": null,
    "defense": null
  },
  {
    "id": "elf_040_cura_do_orvalho_sagrado",
    "name": "Cura do Orvalho Sagrado",
    "type": "ABILITY",
    "race": null,
    "class": null,
    "cost": 2,
    "abilities": [],
    "text": "Cura 5",
    "rarity": "COMMON",
    "image_url": null,
    "effects": [
      {
        "type": "HEAL",
        "value": 5,
        "target": "OWN_GENERAL",
        "trigger": "INSTANT",
        "duration": 0
      }
    ],
    "default_unlocked": true,
    "is_active": true,
    "collection_id": "elf",
    "visual_auras": [],
    "attack": null,
    "defense": null
  },
  {
    "id": "elf_041_derrubar_o_gigante",
    "name": "Derrubar o Gigante",
    "type": "ABILITY",
    "race": null,
    "class": null,
    "cost": 5,
    "abilities": [],
    "text": "—",
    "rarity": "COMMON",
    "image_url": null,
    "effects": [],
    "default_unlocked": true,
    "is_active": true,
    "collection_id": "elf",
    "visual_auras": [],
    "attack": null,
    "defense": null
  },
  {
    "id": "elf_042_santuario_de_folhas",
    "name": "Santuário de Folhas",
    "type": "ABILITY",
    "race": null,
    "class": null,
    "cost": 3,
    "abilities": [],
    "text": "—",
    "rarity": "COMMON",
    "image_url": null,
    "effects": [],
    "default_unlocked": true,
    "is_active": true,
    "collection_id": "elf",
    "visual_auras": [],
    "attack": null,
    "defense": null
  },
  {
    "id": "elf_043_explosao_de_polen",
    "name": "Explosão de Pólen",
    "type": "ABILITY",
    "race": null,
    "class": null,
    "cost": 2,
    "abilities": [],
    "text": "—",
    "rarity": "COMMON",
    "image_url": null,
    "effects": [],
    "default_unlocked": true,
    "is_active": true,
    "collection_id": "elf",
    "visual_auras": [],
    "attack": null,
    "defense": null
  },
  {
    "id": "elf_044_comunhao_com_a_natureza",
    "name": "Comunhão com a Natureza",
    "type": "ABILITY",
    "race": null,
    "class": null,
    "cost": 1,
    "abilities": [],
    "text": "—",
    "rarity": "COMMON",
    "image_url": null,
    "effects": [],
    "default_unlocked": true,
    "is_active": true,
    "collection_id": "elf",
    "visual_auras": [],
    "attack": null,
    "defense": null
  },
  {
    "id": "elf_045_furia_da_floresta",
    "name": "Fúria da Floresta",
    "type": "ABILITY",
    "race": null,
    "class": null,
    "cost": 6,
    "abilities": [],
    "text": "—",
    "rarity": "COMMON",
    "image_url": null,
    "effects": [],
    "default_unlocked": true,
    "is_active": true,
    "collection_id": "elf",
    "visual_auras": [],
    "attack": null,
    "defense": null
  },
  {
    "id": "elf_046_renascimento_verde",
    "name": "Renascimento Verde",
    "type": "ABILITY",
    "race": null,
    "class": null,
    "cost": 4,
    "abilities": [],
    "text": "—",
    "rarity": "COMMON",
    "image_url": null,
    "effects": [],
    "default_unlocked": true,
    "is_active": true,
    "collection_id": "elf",
    "visual_auras": [],
    "attack": null,
    "defense": null
  },
  {
    "id": "elf_047_chicote_de_espinhos",
    "name": "Chicote de Espinhos",
    "type": "ABILITY",
    "race": null,
    "class": null,
    "cost": 2,
    "abilities": [
      "taunt"
    ],
    "text": "Prov. 3 dmg",
    "rarity": "COMMON",
    "image_url": null,
    "effects": [
      {
        "type": "DAMAGE",
        "value": 3,
        "target": "ENEMY_GENERAL",
        "trigger": "INSTANT",
        "duration": 0
      }
    ],
    "default_unlocked": true,
    "is_active": true,
    "collection_id": "elf",
    "visual_auras": [],
    "attack": null,
    "defense": null
  },
  {
    "id": "elf_048_harmonia_do_fluxo",
    "name": "Harmonia do Fluxo",
    "type": "ABILITY",
    "race": null,
    "class": null,
    "cost": 0,
    "abilities": [],
    "text": "—",
    "rarity": "COMMON",
    "image_url": null,
    "effects": [],
    "default_unlocked": true,
    "is_active": true,
    "collection_id": "elf",
    "visual_auras": [],
    "attack": null,
    "defense": null
  },
  {
    "id": "elf_049_nevoa_ilusoria",
    "name": "Névoa Ilusória",
    "type": "ABILITY",
    "race": null,
    "class": null,
    "cost": 3,
    "abilities": [],
    "text": "—",
    "rarity": "COMMON",
    "image_url": null,
    "effects": [],
    "default_unlocked": true,
    "is_active": true,
    "collection_id": "elf",
    "visual_auras": [],
    "attack": null,
    "defense": null
  },
  {
    "id": "elf_050_crescimento_acelerado",
    "name": "Crescimento Acelerado",
    "type": "ABILITY",
    "race": null,
    "class": null,
    "cost": 5,
    "abilities": [],
    "text": "—",
    "rarity": "COMMON",
    "image_url": null,
    "effects": [],
    "default_unlocked": true,
    "is_active": true,
    "collection_id": "elf",
    "visual_auras": [],
    "attack": null,
    "defense": null
  },
  {
    "id": "elf_051_setas_de_vento",
    "name": "Setas de Vento",
    "type": "ABILITY",
    "race": null,
    "class": null,
    "cost": 3,
    "abilities": [],
    "text": "1 dmg",
    "rarity": "COMMON",
    "image_url": null,
    "effects": [
      {
        "type": "DAMAGE",
        "value": 1,
        "target": "ENEMY_GENERAL",
        "trigger": "INSTANT",
        "duration": 0
      }
    ],
    "default_unlocked": true,
    "is_active": true,
    "collection_id": "elf",
    "visual_auras": [],
    "attack": null,
    "defense": null
  },
  {
    "id": "elf_052_despertar_da_floresta",
    "name": "Despertar da Floresta",
    "type": "ABILITY",
    "race": null,
    "class": null,
    "cost": 8,
    "abilities": [
      "taunt"
    ],
    "text": "Prov",
    "rarity": "COMMON",
    "image_url": null,
    "effects": [],
    "default_unlocked": true,
    "is_active": true,
    "collection_id": "elf",
    "visual_auras": [],
    "attack": null,
    "defense": null
  },
  {
    "id": "elf_053_purificacao_natural",
    "name": "Purificação Natural",
    "type": "ABILITY",
    "race": null,
    "class": null,
    "cost": 2,
    "abilities": [],
    "text": "—",
    "rarity": "COMMON",
    "image_url": null,
    "effects": [],
    "default_unlocked": true,
    "is_active": true,
    "collection_id": "elf",
    "visual_auras": [],
    "attack": null,
    "defense": null
  },
  {
    "id": "elf_054_sacrificio_ao_fluxo",
    "name": "Sacrifício ao Fluxo",
    "type": "ABILITY",
    "race": null,
    "class": null,
    "cost": 1,
    "abilities": [],
    "text": "+2 card",
    "rarity": "COMMON",
    "image_url": null,
    "effects": [
      {
        "type": "DRAW",
        "value": 2,
        "target": "OWN_GENERAL",
        "trigger": "INSTANT",
        "duration": 0
      }
    ],
    "default_unlocked": true,
    "is_active": true,
    "collection_id": "elf",
    "visual_auras": [],
    "attack": null,
    "defense": null
  },
  {
    "id": "elf_055_veredito_da_natureza",
    "name": "Veredito da Natureza",
    "type": "ABILITY",
    "race": null,
    "class": null,
    "cost": 7,
    "abilities": [],
    "text": "—",
    "rarity": "COMMON",
    "image_url": null,
    "effects": [],
    "default_unlocked": true,
    "is_active": true,
    "collection_id": "elf",
    "visual_auras": [],
    "attack": null,
    "defense": null
  },
  {
    "id": "elf_056_arco_de_prata_lunar",
    "name": "Arco de Prata Lunar",
    "type": "EQUIPMENT",
    "race": null,
    "class": null,
    "cost": 3,
    "abilities": [
      "taunt"
    ],
    "text": "Prov",
    "rarity": "COMMON",
    "image_url": null,
    "effects": [],
    "default_unlocked": true,
    "is_active": true,
    "collection_id": "elf",
    "visual_auras": [],
    "attack": null,
    "defense": null
  },
  {
    "id": "elf_057_capa_de_camuflagem_de_folhas",
    "name": "Capa de Camuflagem de Folhas",
    "type": "EQUIPMENT",
    "race": null,
    "class": null,
    "cost": 1,
    "abilities": [],
    "text": "—",
    "rarity": "COMMON",
    "image_url": null,
    "effects": [],
    "default_unlocked": true,
    "is_active": true,
    "collection_id": "elf",
    "visual_auras": [],
    "attack": null,
    "defense": null
  },
  {
    "id": "elf_058_cajado_do_anciao",
    "name": "Cajado do Ancião",
    "type": "EQUIPMENT",
    "race": null,
    "class": null,
    "cost": 4,
    "abilities": [],
    "text": "Cura 3",
    "rarity": "COMMON",
    "image_url": null,
    "effects": [],
    "default_unlocked": true,
    "is_active": true,
    "collection_id": "elf",
    "visual_auras": [],
    "attack": null,
    "defense": null
  },
  {
    "id": "elf_059_amuleto_da_floresta_viva",
    "name": "Amuleto da Floresta Viva",
    "type": "EQUIPMENT",
    "race": null,
    "class": null,
    "cost": 2,
    "abilities": [],
    "text": "—",
    "rarity": "COMMON",
    "image_url": null,
    "effects": [],
    "default_unlocked": true,
    "is_active": true,
    "collection_id": "elf",
    "visual_auras": [],
    "attack": null,
    "defense": null
  },
  {
    "id": "elf_060_lamina_de_vento_cortante",
    "name": "Lâmina de Vento Cortante",
    "type": "EQUIPMENT",
    "race": null,
    "class": null,
    "cost": 2,
    "abilities": [
      "rush"
    ],
    "text": "Ini",
    "rarity": "COMMON",
    "image_url": null,
    "effects": [],
    "default_unlocked": true,
    "is_active": true,
    "collection_id": "elf",
    "visual_auras": [],
    "attack": null,
    "defense": null
  },
  {
    "id": "elf_061_escudo_de_casca_de_ferro",
    "name": "Escudo de Casca de Ferro",
    "type": "EQUIPMENT",
    "race": null,
    "class": null,
    "cost": 3,
    "abilities": [
      "taunt"
    ],
    "text": "Prov",
    "rarity": "COMMON",
    "image_url": null,
    "effects": [],
    "default_unlocked": true,
    "is_active": true,
    "collection_id": "elf",
    "visual_auras": [],
    "attack": null,
    "defense": null
  },
  {
    "id": "elf_062_aljava_de_flechas_infinitas",
    "name": "Aljava de Flechas Infinitas",
    "type": "EQUIPMENT",
    "race": null,
    "class": null,
    "cost": 4,
    "abilities": [],
    "text": "—",
    "rarity": "COMMON",
    "image_url": null,
    "effects": [],
    "default_unlocked": true,
    "is_active": true,
    "collection_id": "elf",
    "visual_auras": [],
    "attack": null,
    "defense": null
  },
  {
    "id": "elf_063_botas_do_passo_agil",
    "name": "Botas do Passo Ágil",
    "type": "EQUIPMENT",
    "race": null,
    "class": null,
    "cost": 1,
    "abilities": [],
    "text": "—",
    "rarity": "COMMON",
    "image_url": null,
    "effects": [],
    "default_unlocked": true,
    "is_active": true,
    "collection_id": "elf",
    "visual_auras": [],
    "attack": null,
    "defense": null
  },
  {
    "id": "elf_064_diadema_da_realeza_elfica",
    "name": "Diadema da Realeza Élfica",
    "type": "EQUIPMENT",
    "race": null,
    "class": null,
    "cost": 5,
    "abilities": [],
    "text": "—",
    "rarity": "COMMON",
    "image_url": null,
    "effects": [],
    "default_unlocked": true,
    "is_active": true,
    "collection_id": "elf",
    "visual_auras": [],
    "attack": null,
    "defense": null
  },
  {
    "id": "elf_065_flauta_de_pan_encantada",
    "name": "Flauta de Pan Encantada",
    "type": "EQUIPMENT",
    "race": null,
    "class": null,
    "cost": 3,
    "abilities": [],
    "text": "—",
    "rarity": "COMMON",
    "image_url": null,
    "effects": [],
    "default_unlocked": true,
    "is_active": true,
    "collection_id": "elf",
    "visual_auras": [],
    "attack": null,
    "defense": null
  },
  {
    "id": "elf_066_manoplas_de_forca_terrestre",
    "name": "Manoplas de Força Terrestre",
    "type": "EQUIPMENT",
    "race": null,
    "class": null,
    "cost": 4,
    "abilities": [],
    "text": "—",
    "rarity": "COMMON",
    "image_url": null,
    "effects": [],
    "default_unlocked": true,
    "is_active": true,
    "collection_id": "elf",
    "visual_auras": [],
    "attack": null,
    "defense": null
  },
  {
    "id": "elf_067_colar_de_lagrimas_de_unicornio",
    "name": "Colar de Lágrimas de Unicórnio",
    "type": "EQUIPMENT",
    "race": null,
    "class": null,
    "cost": 6,
    "abilities": [],
    "text": "—",
    "rarity": "COMMON",
    "image_url": null,
    "effects": [],
    "default_unlocked": true,
    "is_active": true,
    "collection_id": "elf",
    "visual_auras": [],
    "attack": null,
    "defense": null
  },
  {
    "id": "elf_068_estandarte_da_floresta_unida",
    "name": "Estandarte da Floresta Unida",
    "type": "EQUIPMENT",
    "race": null,
    "class": null,
    "cost": 5,
    "abilities": [],
    "text": "—",
    "rarity": "COMMON",
    "image_url": null,
    "effects": [],
    "default_unlocked": true,
    "is_active": true,
    "collection_id": "elf",
    "visual_auras": [],
    "attack": null,
    "defense": null
  },
  {
    "id": "elf_069_anel_do_ciclo_eterno",
    "name": "Anel do Ciclo Eterno",
    "type": "EQUIPMENT",
    "race": null,
    "class": null,
    "cost": 2,
    "abilities": [],
    "text": "—",
    "rarity": "COMMON",
    "image_url": null,
    "effects": [],
    "default_unlocked": true,
    "is_active": true,
    "collection_id": "elf",
    "visual_auras": [],
    "attack": null,
    "defense": null
  },
  {
    "id": "elf_070_chifre_de_guerra_de_eldoria",
    "name": "Chifre de Guerra de Eldoria",
    "type": "EQUIPMENT",
    "race": null,
    "class": null,
    "cost": 10,
    "abilities": [],
    "text": "—",
    "rarity": "COMMON",
    "image_url": null,
    "effects": [],
    "default_unlocked": true,
    "is_active": true,
    "collection_id": "elf",
    "visual_auras": [],
    "attack": null,
    "defense": null
  }
] as unknown as Card[];
