import type { Card } from '../../../shared/types';

export const GOBLIN_COLLECTION = {
  id: 'goblin',
  name: 'Goblins',
  description: 'Caos nas Terras Ermas — Goblins'
};

// NOTE: type/rarity are stored as UPPERCASE strings for Godot UI compatibility.
export const GOBLIN_CARD_CATALOG: Array<Card> = [
  {
    "id": "gbl_001_recruta_da_vanguarda_putrida",
    "name": "Recruta da Vanguarda Pútrida",
    "type": "DEFENDER",
    "race": null,
    "class": null,
    "cost": 1,
    "attack": 2,
    "defense": 1,
    "abilities": [],
    "text": "—",
    "rarity": "COMMON",
    "image_url": null,
    "effects": [],
    "default_unlocked": true,
    "is_active": true,
    "collection_id": "goblin",
    "visual_auras": []
  },
  {
    "id": "gbl_002_piromaniaco_de_latao",
    "name": "Piromaníaco de Latão",
    "type": "DEFENDER",
    "race": null,
    "class": null,
    "cost": 2,
    "attack": 2,
    "defense": 1,
    "abilities": [],
    "text": "1 dmg",
    "rarity": "COMMON",
    "image_url": null,
    "effects": [
      {
        "type": "damage",
        "value": 1,
        "target": "ENEMY_GENERAL",
        "trigger": "INSTANT",
        "duration": 0
      }
    ],
    "default_unlocked": true,
    "is_active": true,
    "collection_id": "goblin",
    "visual_auras": []
  },
  {
    "id": "gbl_003_tamborileiro_de_guerra",
    "name": "Tamborileiro de Guerra",
    "type": "DEFENDER",
    "race": null,
    "class": null,
    "cost": 2,
    "attack": 1,
    "defense": 3,
    "abilities": [
      "rush"
    ],
    "text": "Ini",
    "rarity": "COMMON",
    "image_url": null,
    "effects": [],
    "default_unlocked": true,
    "is_active": true,
    "collection_id": "goblin",
    "visual_auras": []
  },
  {
    "id": "gbl_004_lancador_de_sucata",
    "name": "Lançador de Sucata",
    "type": "DEFENDER",
    "race": null,
    "class": null,
    "cost": 3,
    "attack": 3,
    "defense": 2,
    "abilities": [],
    "text": "—",
    "rarity": "COMMON",
    "image_url": null,
    "effects": [],
    "default_unlocked": true,
    "is_active": true,
    "collection_id": "goblin",
    "visual_auras": []
  },
  {
    "id": "gbl_005_batedor_de_trincheira",
    "name": "Batedor de Trincheira",
    "type": "DEFENDER",
    "race": null,
    "class": null,
    "cost": 1,
    "attack": 1,
    "defense": 1,
    "abilities": [
      "rush"
    ],
    "text": "Ini",
    "rarity": "COMMON",
    "image_url": null,
    "effects": [],
    "default_unlocked": true,
    "is_active": true,
    "collection_id": "goblin",
    "visual_auras": []
  },
  {
    "id": "gbl_006_xama_da_chama_caotica",
    "name": "Xamã da Chama Caótica",
    "type": "DEFENDER",
    "race": null,
    "class": null,
    "cost": 4,
    "attack": 3,
    "defense": 3,
    "abilities": [
      "taunt"
    ],
    "text": "Prov",
    "rarity": "COMMON",
    "image_url": null,
    "effects": [],
    "default_unlocked": true,
    "is_active": true,
    "collection_id": "goblin",
    "visual_auras": []
  },
  {
    "id": "gbl_007_mestre_de_bando_krog",
    "name": "Mestre de Bando Krog",
    "type": "DEFENDER",
    "race": null,
    "class": null,
    "cost": 5,
    "attack": 4,
    "defense": 4,
    "abilities": [],
    "text": "1 dmg",
    "rarity": "COMMON",
    "image_url": null,
    "effects": [
      {
        "type": "damage",
        "value": 1,
        "target": "ENEMY_GENERAL",
        "trigger": "INSTANT",
        "duration": 0
      }
    ],
    "default_unlocked": true,
    "is_active": true,
    "collection_id": "goblin",
    "visual_auras": []
  },
  {
    "id": "gbl_008_ladrao_de_reliquias",
    "name": "Ladrão de Relíquias",
    "type": "DEFENDER",
    "race": null,
    "class": null,
    "cost": 2,
    "attack": 2,
    "defense": 2,
    "abilities": [],
    "text": "—",
    "rarity": "COMMON",
    "image_url": null,
    "effects": [],
    "default_unlocked": true,
    "is_active": true,
    "collection_id": "goblin",
    "visual_auras": []
  },
  {
    "id": "gbl_009_engenheiro_de_explosivos",
    "name": "Engenheiro de Explosivos",
    "type": "DEFENDER",
    "race": null,
    "class": null,
    "cost": 3,
    "attack": 2,
    "defense": 3,
    "abilities": [],
    "text": "—",
    "rarity": "COMMON",
    "image_url": null,
    "effects": [],
    "default_unlocked": true,
    "is_active": true,
    "collection_id": "goblin",
    "visual_auras": []
  },
  {
    "id": "gbl_010_cavaleiro_de_lobo_faminto",
    "name": "Cavaleiro de Lobo Faminto",
    "type": "DEFENDER",
    "race": null,
    "class": null,
    "cost": 4,
    "attack": 5,
    "defense": 2,
    "abilities": [
      "rush",
      "taunt"
    ],
    "text": "Ini,Prov",
    "rarity": "COMMON",
    "image_url": null,
    "effects": [],
    "default_unlocked": true,
    "is_active": true,
    "collection_id": "goblin",
    "visual_auras": []
  },
  {
    "id": "gbl_011_assassino_das_sombras_verdes",
    "name": "Assassino das Sombras Verdes",
    "type": "DEFENDER",
    "race": null,
    "class": null,
    "cost": 3,
    "attack": 3,
    "defense": 1,
    "abilities": [],
    "text": "—",
    "rarity": "COMMON",
    "image_url": null,
    "effects": [],
    "default_unlocked": true,
    "is_active": true,
    "collection_id": "goblin",
    "visual_auras": []
  },
  {
    "id": "gbl_012_goblin_coletor_de_taxas",
    "name": "Goblin Coletor de Taxas",
    "type": "DEFENDER",
    "race": null,
    "class": null,
    "cost": 2,
    "attack": 2,
    "defense": 2,
    "abilities": [],
    "text": "—",
    "rarity": "COMMON",
    "image_url": null,
    "effects": [],
    "default_unlocked": true,
    "is_active": true,
    "collection_id": "goblin",
    "visual_auras": []
  },
  {
    "id": "gbl_013_mentor_da_horda",
    "name": "Mentor da Horda",
    "type": "DEFENDER",
    "race": null,
    "class": null,
    "cost": 4,
    "attack": 3,
    "defense": 4,
    "abilities": [
      "rush"
    ],
    "text": "Ini",
    "rarity": "COMMON",
    "image_url": null,
    "effects": [],
    "default_unlocked": true,
    "is_active": true,
    "collection_id": "goblin",
    "visual_auras": []
  },
  {
    "id": "gbl_014_goblin_de_assalto_aereo",
    "name": "Goblin de Assalto Aéreo",
    "type": "DEFENDER",
    "race": null,
    "class": null,
    "cost": 3,
    "attack": 3,
    "defense": 1,
    "abilities": [
      "taunt"
    ],
    "text": "Prov",
    "rarity": "COMMON",
    "image_url": null,
    "effects": [],
    "default_unlocked": true,
    "is_active": true,
    "collection_id": "goblin",
    "visual_auras": []
  },
  {
    "id": "gbl_015_comerciante_de_mercado_negro",
    "name": "Comerciante de Mercado Negro",
    "type": "DEFENDER",
    "race": null,
    "class": null,
    "cost": 2,
    "attack": 1,
    "defense": 2,
    "abilities": [],
    "text": "—",
    "rarity": "COMMON",
    "image_url": null,
    "effects": [],
    "default_unlocked": true,
    "is_active": true,
    "collection_id": "goblin",
    "visual_auras": []
  },
  {
    "id": "gbl_016_berserker_da_montanha_rubra",
    "name": "Berserker da Montanha Rubra",
    "type": "DEFENDER",
    "race": null,
    "class": null,
    "cost": 4,
    "attack": 6,
    "defense": 1,
    "abilities": [],
    "text": "—",
    "rarity": "COMMON",
    "image_url": null,
    "effects": [],
    "default_unlocked": true,
    "is_active": true,
    "collection_id": "goblin",
    "visual_auras": []
  },
  {
    "id": "gbl_017_goblin_reciclador",
    "name": "Goblin Reciclador",
    "type": "DEFENDER",
    "race": null,
    "class": null,
    "cost": 3,
    "attack": 2,
    "defense": 2,
    "abilities": [],
    "text": "—",
    "rarity": "COMMON",
    "image_url": null,
    "effects": [],
    "default_unlocked": true,
    "is_active": true,
    "collection_id": "goblin",
    "visual_auras": []
  },
  {
    "id": "gbl_018_arauto_do_apocalipse_verde",
    "name": "Arauto do Apocalipse Verde",
    "type": "DEFENDER",
    "race": null,
    "class": null,
    "cost": 6,
    "attack": 5,
    "defense": 5,
    "abilities": [],
    "text": "—",
    "rarity": "COMMON",
    "image_url": null,
    "effects": [],
    "default_unlocked": true,
    "is_active": true,
    "collection_id": "goblin",
    "visual_auras": []
  },
  {
    "id": "gbl_019_general_de_guerra_zog",
    "name": "General de Guerra Zog",
    "type": "DEFENDER",
    "race": null,
    "class": null,
    "cost": 8,
    "attack": 7,
    "defense": 7,
    "abilities": [
      "rush"
    ],
    "text": "Ini",
    "rarity": "COMMON",
    "image_url": null,
    "effects": [],
    "default_unlocked": true,
    "is_active": true,
    "collection_id": "goblin",
    "visual_auras": []
  },
  {
    "id": "gbl_020_o_colosso_de_lixo",
    "name": "O Colosso de Lixo",
    "type": "DEFENDER",
    "race": null,
    "class": null,
    "cost": 10,
    "attack": 10,
    "defense": 10,
    "abilities": [
      "taunt"
    ],
    "text": "Prov",
    "rarity": "COMMON",
    "image_url": null,
    "effects": [],
    "default_unlocked": true,
    "is_active": true,
    "collection_id": "goblin",
    "visual_auras": []
  },
  {
    "id": "gbl_021_grunt_das_cavernas",
    "name": "Grunt das Cavernas",
    "type": "DEFENDER",
    "race": null,
    "class": null,
    "cost": 0,
    "attack": 1,
    "defense": 1,
    "abilities": [],
    "text": "—",
    "rarity": "COMMON",
    "image_url": null,
    "effects": [],
    "default_unlocked": true,
    "is_active": true,
    "collection_id": "goblin",
    "visual_auras": []
  },
  {
    "id": "gbl_022_espadachim_de_aluguel",
    "name": "Espadachim de Aluguel",
    "type": "DEFENDER",
    "race": null,
    "class": null,
    "cost": 1,
    "attack": 2,
    "defense": 1,
    "abilities": [],
    "text": "—",
    "rarity": "COMMON",
    "image_url": null,
    "effects": [],
    "default_unlocked": true,
    "is_active": true,
    "collection_id": "goblin",
    "visual_auras": []
  },
  {
    "id": "gbl_023_arremessador_de_pedras",
    "name": "Arremessador de Pedras",
    "type": "DEFENDER",
    "race": null,
    "class": null,
    "cost": 1,
    "attack": 1,
    "defense": 2,
    "abilities": [],
    "text": "—",
    "rarity": "COMMON",
    "image_url": null,
    "effects": [],
    "default_unlocked": true,
    "is_active": true,
    "collection_id": "goblin",
    "visual_auras": []
  },
  {
    "id": "gbl_024_briguento_de_taverna",
    "name": "Briguento de Taverna",
    "type": "DEFENDER",
    "race": null,
    "class": null,
    "cost": 2,
    "attack": 3,
    "defense": 1,
    "abilities": [],
    "text": "—",
    "rarity": "COMMON",
    "image_url": null,
    "effects": [],
    "default_unlocked": true,
    "is_active": true,
    "collection_id": "goblin",
    "visual_auras": []
  },
  {
    "id": "gbl_025_goblin_da_guarda_costeira",
    "name": "Goblin da Guarda Costeira",
    "type": "DEFENDER",
    "race": null,
    "class": null,
    "cost": 2,
    "attack": 2,
    "defense": 2,
    "abilities": [],
    "text": "—",
    "rarity": "COMMON",
    "image_url": null,
    "effects": [],
    "default_unlocked": true,
    "is_active": true,
    "collection_id": "goblin",
    "visual_auras": []
  },
  {
    "id": "gbl_026_saqueador_de_tumbas",
    "name": "Saqueador de Tumbas",
    "type": "DEFENDER",
    "race": null,
    "class": null,
    "cost": 2,
    "attack": 3,
    "defense": 2,
    "abilities": [],
    "text": "—",
    "rarity": "COMMON",
    "image_url": null,
    "effects": [],
    "default_unlocked": true,
    "is_active": true,
    "collection_id": "goblin",
    "visual_auras": []
  },
  {
    "id": "gbl_027_guerreiro_de_elite_da_horda",
    "name": "Guerreiro de Elite da Horda",
    "type": "DEFENDER",
    "race": null,
    "class": null,
    "cost": 3,
    "attack": 4,
    "defense": 2,
    "abilities": [],
    "text": "—",
    "rarity": "COMMON",
    "image_url": null,
    "effects": [],
    "default_unlocked": true,
    "is_active": true,
    "collection_id": "goblin",
    "visual_auras": []
  },
  {
    "id": "gbl_028_lenhador_goblin",
    "name": "Lenhador Goblin",
    "type": "DEFENDER",
    "race": null,
    "class": null,
    "cost": 3,
    "attack": 3,
    "defense": 3,
    "abilities": [],
    "text": "—",
    "rarity": "COMMON",
    "image_url": null,
    "effects": [],
    "default_unlocked": true,
    "is_active": true,
    "collection_id": "goblin",
    "visual_auras": []
  },
  {
    "id": "gbl_029_patrulheiro_do_pantano",
    "name": "Patrulheiro do Pântano",
    "type": "DEFENDER",
    "race": null,
    "class": null,
    "cost": 3,
    "attack": 4,
    "defense": 3,
    "abilities": [],
    "text": "—",
    "rarity": "COMMON",
    "image_url": null,
    "effects": [],
    "default_unlocked": true,
    "is_active": true,
    "collection_id": "goblin",
    "visual_auras": []
  },
  {
    "id": "gbl_030_veterano_de_cem_batalhas",
    "name": "Veterano de Cem Batalhas",
    "type": "DEFENDER",
    "race": null,
    "class": null,
    "cost": 4,
    "attack": 5,
    "defense": 3,
    "abilities": [],
    "text": "—",
    "rarity": "COMMON",
    "image_url": null,
    "effects": [],
    "default_unlocked": true,
    "is_active": true,
    "collection_id": "goblin",
    "visual_auras": []
  },
  {
    "id": "gbl_031_campeao_do_fosso",
    "name": "Campeão do Fosso",
    "type": "DEFENDER",
    "race": null,
    "class": null,
    "cost": 4,
    "attack": 4,
    "defense": 4,
    "abilities": [],
    "text": "—",
    "rarity": "COMMON",
    "image_url": null,
    "effects": [],
    "default_unlocked": true,
    "is_active": true,
    "collection_id": "goblin",
    "visual_auras": []
  },
  {
    "id": "gbl_032_destruidor_de_portoes",
    "name": "Destruidor de Portões",
    "type": "DEFENDER",
    "race": null,
    "class": null,
    "cost": 5,
    "attack": 6,
    "defense": 4,
    "abilities": [],
    "text": "—",
    "rarity": "COMMON",
    "image_url": null,
    "effects": [],
    "default_unlocked": true,
    "is_active": true,
    "collection_id": "goblin",
    "visual_auras": []
  },
  {
    "id": "gbl_033_guardiao_da_montanha",
    "name": "Guardião da Montanha",
    "type": "DEFENDER",
    "race": null,
    "class": null,
    "cost": 5,
    "attack": 5,
    "defense": 5,
    "abilities": [],
    "text": "—",
    "rarity": "COMMON",
    "image_url": null,
    "effects": [],
    "default_unlocked": true,
    "is_active": true,
    "collection_id": "goblin",
    "visual_auras": []
  },
  {
    "id": "gbl_034_carrasco_da_horda",
    "name": "Carrasco da Horda",
    "type": "DEFENDER",
    "race": null,
    "class": null,
    "cost": 6,
    "attack": 7,
    "defense": 4,
    "abilities": [],
    "text": "—",
    "rarity": "COMMON",
    "image_url": null,
    "effects": [],
    "default_unlocked": true,
    "is_active": true,
    "collection_id": "goblin",
    "visual_auras": []
  },
  {
    "id": "gbl_035_o_grande_bruto",
    "name": "O Grande Bruto",
    "type": "DEFENDER",
    "race": null,
    "class": null,
    "cost": 7,
    "attack": 8,
    "defense": 6,
    "abilities": [],
    "text": "—",
    "rarity": "COMMON",
    "image_url": null,
    "effects": [],
    "default_unlocked": true,
    "is_active": true,
    "collection_id": "goblin",
    "visual_auras": []
  },
  {
    "id": "gbl_036_explosao_de_sucata",
    "name": "Explosão de Sucata",
    "type": "ABILITY",
    "race": null,
    "class": null,
    "cost": 1,
    "attack": null,
    "defense": null,
    "abilities": [],
    "text": "2 dmg",
    "rarity": "COMMON",
    "image_url": null,
    "effects": [
      {
        "type": "damage",
        "value": 2,
        "target": "ENEMY_GENERAL",
        "trigger": "INSTANT",
        "duration": 0
      }
    ],
    "default_unlocked": true,
    "is_active": true,
    "collection_id": "goblin",
    "visual_auras": []
  },
  {
    "id": "gbl_037_chamado_da_horda",
    "name": "Chamado da Horda",
    "type": "ABILITY",
    "race": null,
    "class": null,
    "cost": 4,
    "attack": null,
    "defense": null,
    "abilities": [
      "rush"
    ],
    "text": "Ini",
    "rarity": "COMMON",
    "image_url": null,
    "effects": [],
    "default_unlocked": true,
    "is_active": true,
    "collection_id": "goblin",
    "visual_auras": []
  },
  {
    "id": "gbl_038_furia_frenetica",
    "name": "Fúria Frenética",
    "type": "ABILITY",
    "race": null,
    "class": null,
    "cost": 2,
    "attack": null,
    "defense": null,
    "abilities": [],
    "text": "—",
    "rarity": "COMMON",
    "image_url": null,
    "effects": [],
    "default_unlocked": true,
    "is_active": true,
    "collection_id": "goblin",
    "visual_auras": []
  },
  {
    "id": "gbl_039_roubo_descarado",
    "name": "Roubo Descarado",
    "type": "ABILITY",
    "race": null,
    "class": null,
    "cost": 3,
    "attack": null,
    "defense": null,
    "abilities": [],
    "text": "—",
    "rarity": "COMMON",
    "image_url": null,
    "effects": [],
    "default_unlocked": true,
    "is_active": true,
    "collection_id": "goblin",
    "visual_auras": []
  },
  {
    "id": "gbl_040_chuva_de_flechas_de_fogo",
    "name": "Chuva de Flechas de Fogo",
    "type": "ABILITY",
    "race": null,
    "class": null,
    "cost": 5,
    "attack": null,
    "defense": null,
    "abilities": [],
    "text": "—",
    "rarity": "COMMON",
    "image_url": null,
    "effects": [],
    "default_unlocked": true,
    "is_active": true,
    "collection_id": "goblin",
    "visual_auras": []
  },
  {
    "id": "gbl_041_sacrificio_para_o_idolo",
    "name": "Sacrifício para o Ídolo",
    "type": "ABILITY",
    "race": null,
    "class": null,
    "cost": 2,
    "attack": null,
    "defense": null,
    "abilities": [],
    "text": "—",
    "rarity": "COMMON",
    "image_url": null,
    "effects": [],
    "default_unlocked": true,
    "is_active": true,
    "collection_id": "goblin",
    "visual_auras": []
  },
  {
    "id": "gbl_042_grito_de_guerra_ensurdecedor",
    "name": "Grito de Guerra Ensurdecedor",
    "type": "ABILITY",
    "race": null,
    "class": null,
    "cost": 3,
    "attack": null,
    "defense": null,
    "abilities": [],
    "text": "—",
    "rarity": "COMMON",
    "image_url": null,
    "effects": [],
    "default_unlocked": true,
    "is_active": true,
    "collection_id": "goblin",
    "visual_auras": []
  },
  {
    "id": "gbl_043_oleo_escorregadio",
    "name": "Óleo Escorregadio",
    "type": "ABILITY",
    "race": null,
    "class": null,
    "cost": 1,
    "attack": null,
    "defense": null,
    "abilities": [],
    "text": "—",
    "rarity": "COMMON",
    "image_url": null,
    "effects": [],
    "default_unlocked": true,
    "is_active": true,
    "collection_id": "goblin",
    "visual_auras": []
  },
  {
    "id": "gbl_044_alquimia_instavel",
    "name": "Alquimia Instável",
    "type": "ABILITY",
    "race": null,
    "class": null,
    "cost": 4,
    "attack": null,
    "defense": null,
    "abilities": [],
    "text": "—",
    "rarity": "COMMON",
    "image_url": null,
    "effects": [],
    "default_unlocked": true,
    "is_active": true,
    "collection_id": "goblin",
    "visual_auras": []
  },
  {
    "id": "gbl_045_marcha_funebre",
    "name": "Marcha Fúnebre",
    "type": "ABILITY",
    "race": null,
    "class": null,
    "cost": 6,
    "attack": null,
    "defense": null,
    "abilities": [],
    "text": "—",
    "rarity": "COMMON",
    "image_url": null,
    "effects": [],
    "default_unlocked": true,
    "is_active": true,
    "collection_id": "goblin",
    "visual_auras": []
  },
  {
    "id": "gbl_046_plano_caotico",
    "name": "Plano Caótico",
    "type": "ABILITY",
    "race": null,
    "class": null,
    "cost": 0,
    "attack": null,
    "defense": null,
    "abilities": [],
    "text": "3 dmg",
    "rarity": "COMMON",
    "image_url": null,
    "effects": [
      {
        "type": "damage",
        "value": 3,
        "target": "ENEMY_GENERAL",
        "trigger": "INSTANT",
        "duration": 0
      }
    ],
    "default_unlocked": true,
    "is_active": true,
    "collection_id": "goblin",
    "visual_auras": []
  },
  {
    "id": "gbl_047_armadura_de_sucata_instantanea",
    "name": "Armadura de Sucata Instantânea",
    "type": "ABILITY",
    "race": null,
    "class": null,
    "cost": 2,
    "attack": null,
    "defense": null,
    "abilities": [
      "taunt"
    ],
    "text": "Prov",
    "rarity": "COMMON",
    "image_url": null,
    "effects": [],
    "default_unlocked": true,
    "is_active": true,
    "collection_id": "goblin",
    "visual_auras": []
  },
  {
    "id": "gbl_048_sabotagem",
    "name": "Sabotagem",
    "type": "ABILITY",
    "race": null,
    "class": null,
    "cost": 3,
    "attack": null,
    "defense": null,
    "abilities": [],
    "text": "—",
    "rarity": "COMMON",
    "image_url": null,
    "effects": [],
    "default_unlocked": true,
    "is_active": true,
    "collection_id": "goblin",
    "visual_auras": []
  },
  {
    "id": "gbl_049_banquete_de_carne_estranha",
    "name": "Banquete de Carne Estranha",
    "type": "ABILITY",
    "race": null,
    "class": null,
    "cost": 3,
    "attack": null,
    "defense": null,
    "abilities": [],
    "text": "—",
    "rarity": "COMMON",
    "image_url": null,
    "effects": [],
    "default_unlocked": true,
    "is_active": true,
    "collection_id": "goblin",
    "visual_auras": []
  },
  {
    "id": "gbl_050_inspiracao_explosiva",
    "name": "Inspiração Explosiva",
    "type": "ABILITY",
    "race": null,
    "class": null,
    "cost": 2,
    "attack": null,
    "defense": null,
    "abilities": [
      "rush"
    ],
    "text": "Ini",
    "rarity": "COMMON",
    "image_url": null,
    "effects": [],
    "default_unlocked": true,
    "is_active": true,
    "collection_id": "goblin",
    "visual_auras": []
  },
  {
    "id": "gbl_051_terremoto_de_pulos",
    "name": "Terremoto de Pulos",
    "type": "ABILITY",
    "race": null,
    "class": null,
    "cost": 5,
    "attack": null,
    "defense": null,
    "abilities": [],
    "text": "—",
    "rarity": "COMMON",
    "image_url": null,
    "effects": [],
    "default_unlocked": true,
    "is_active": true,
    "collection_id": "goblin",
    "visual_auras": []
  },
  {
    "id": "gbl_052_oferta_irrecusavel",
    "name": "Oferta Irrecusável",
    "type": "ABILITY",
    "race": null,
    "class": null,
    "cost": 4,
    "attack": null,
    "defense": null,
    "abilities": [],
    "text": "—",
    "rarity": "COMMON",
    "image_url": null,
    "effects": [],
    "default_unlocked": true,
    "is_active": true,
    "collection_id": "goblin",
    "visual_auras": []
  },
  {
    "id": "gbl_053_tunel_de_fuga",
    "name": "Túnel de Fuga",
    "type": "ABILITY",
    "race": null,
    "class": null,
    "cost": 2,
    "attack": null,
    "defense": null,
    "abilities": [],
    "text": "—",
    "rarity": "COMMON",
    "image_url": null,
    "effects": [],
    "default_unlocked": true,
    "is_active": true,
    "collection_id": "goblin",
    "visual_auras": []
  },
  {
    "id": "gbl_054_bencao_do_rei_rato",
    "name": "Bênção do Rei Rato",
    "type": "ABILITY",
    "race": null,
    "class": null,
    "cost": 1,
    "attack": null,
    "defense": null,
    "abilities": [
      "poison"
    ],
    "text": "Ven",
    "rarity": "COMMON",
    "image_url": null,
    "effects": [],
    "default_unlocked": true,
    "is_active": true,
    "collection_id": "goblin",
    "visual_auras": []
  },
  {
    "id": "gbl_055_apocalipse_de_sucata",
    "name": "Apocalipse de Sucata",
    "type": "ABILITY",
    "race": null,
    "class": null,
    "cost": 9,
    "attack": null,
    "defense": null,
    "abilities": [],
    "text": "1 dmg",
    "rarity": "COMMON",
    "image_url": null,
    "effects": [
      {
        "type": "damage",
        "value": 1,
        "target": "ENEMY_GENERAL",
        "trigger": "INSTANT",
        "duration": 0
      }
    ],
    "default_unlocked": true,
    "is_active": true,
    "collection_id": "goblin",
    "visual_auras": []
  },
  {
    "id": "gbl_056_adaga_de_vidro_quebrado",
    "name": "Adaga de Vidro Quebrado",
    "type": "EQUIPMENT",
    "race": null,
    "class": null,
    "cost": 1,
    "attack": null,
    "defense": null,
    "abilities": [],
    "text": "—",
    "rarity": "COMMON",
    "image_url": null,
    "effects": [],
    "default_unlocked": true,
    "is_active": true,
    "collection_id": "goblin",
    "visual_auras": []
  },
  {
    "id": "gbl_057_estandarte_da_horda_imunda",
    "name": "Estandarte da Horda Imunda",
    "type": "EQUIPMENT",
    "race": null,
    "class": null,
    "cost": 3,
    "attack": null,
    "defense": null,
    "abilities": [],
    "text": "—",
    "rarity": "COMMON",
    "image_url": null,
    "effects": [],
    "default_unlocked": true,
    "is_active": true,
    "collection_id": "goblin",
    "visual_auras": []
  },
  {
    "id": "gbl_058_catapulta_de_lancamento_humano_goblin",
    "name": "Catapulta de Lançamento Humano (Goblin)",
    "type": "EQUIPMENT",
    "race": null,
    "class": null,
    "cost": 4,
    "attack": null,
    "defense": null,
    "abilities": [
      "rush"
    ],
    "text": "Ini",
    "rarity": "COMMON",
    "image_url": null,
    "effects": [],
    "default_unlocked": true,
    "is_active": true,
    "collection_id": "goblin",
    "visual_auras": []
  },
  {
    "id": "gbl_059_escudo_de_tampa_de_caldeirao",
    "name": "Escudo de Tampa de Caldeirão",
    "type": "EQUIPMENT",
    "race": null,
    "class": null,
    "cost": 2,
    "attack": null,
    "defense": null,
    "abilities": [
      "taunt"
    ],
    "text": "Prov",
    "rarity": "COMMON",
    "image_url": null,
    "effects": [],
    "default_unlocked": true,
    "is_active": true,
    "collection_id": "goblin",
    "visual_auras": []
  },
  {
    "id": "gbl_060_amuleto_de_dente_de_ogro",
    "name": "Amuleto de Dente de Ogro",
    "type": "EQUIPMENT",
    "race": null,
    "class": null,
    "cost": 2,
    "attack": null,
    "defense": null,
    "abilities": [
      "rush"
    ],
    "text": "Ini",
    "rarity": "COMMON",
    "image_url": null,
    "effects": [],
    "default_unlocked": true,
    "is_active": true,
    "collection_id": "goblin",
    "visual_auras": []
  },
  {
    "id": "gbl_061_tambor_de_guerra_de_pele_de_troll",
    "name": "Tambor de Guerra de Pele de Troll",
    "type": "EQUIPMENT",
    "race": null,
    "class": null,
    "cost": 5,
    "attack": null,
    "defense": null,
    "abilities": [],
    "text": "—",
    "rarity": "COMMON",
    "image_url": null,
    "effects": [],
    "default_unlocked": true,
    "is_active": true,
    "collection_id": "goblin",
    "visual_auras": []
  },
  {
    "id": "gbl_062_capa_de_invisibilidade_barata",
    "name": "Capa de Invisibilidade Barata",
    "type": "EQUIPMENT",
    "race": null,
    "class": null,
    "cost": 3,
    "attack": null,
    "defense": null,
    "abilities": [],
    "text": "—",
    "rarity": "COMMON",
    "image_url": null,
    "effects": [],
    "default_unlocked": true,
    "is_active": true,
    "collection_id": "goblin",
    "visual_auras": []
  },
  {
    "id": "gbl_063_lanca_chamas_de_sucata",
    "name": "Lança-Chamas de Sucata",
    "type": "EQUIPMENT",
    "race": null,
    "class": null,
    "cost": 4,
    "attack": null,
    "defense": null,
    "abilities": [],
    "text": "—",
    "rarity": "COMMON",
    "image_url": null,
    "effects": [],
    "default_unlocked": true,
    "is_active": true,
    "collection_id": "goblin",
    "visual_auras": []
  },
  {
    "id": "gbl_064_botas_de_corrida_explosiva",
    "name": "Botas de Corrida Explosiva",
    "type": "EQUIPMENT",
    "race": null,
    "class": null,
    "cost": 1,
    "attack": null,
    "defense": null,
    "abilities": [
      "rush"
    ],
    "text": "Ini",
    "rarity": "COMMON",
    "image_url": null,
    "effects": [],
    "default_unlocked": true,
    "is_active": true,
    "collection_id": "goblin",
    "visual_auras": []
  },
  {
    "id": "gbl_065_maquina_de_clonagem_falha",
    "name": "Máquina de Clonagem Falha",
    "type": "EQUIPMENT",
    "race": null,
    "class": null,
    "cost": 6,
    "attack": null,
    "defense": null,
    "abilities": [],
    "text": "—",
    "rarity": "COMMON",
    "image_url": null,
    "effects": [],
    "default_unlocked": true,
    "is_active": true,
    "collection_id": "goblin",
    "visual_auras": []
  },
  {
    "id": "gbl_066_martelo_de_impacto_de_zog",
    "name": "Martelo de Impacto de Zog",
    "type": "EQUIPMENT",
    "race": null,
    "class": null,
    "cost": 5,
    "attack": null,
    "defense": null,
    "abilities": [],
    "text": "—",
    "rarity": "COMMON",
    "image_url": null,
    "effects": [],
    "default_unlocked": true,
    "is_active": true,
    "collection_id": "goblin",
    "visual_auras": []
  },
  {
    "id": "gbl_067_colar_de_orelhas_de_elfo",
    "name": "Colar de Orelhas de Elfo",
    "type": "EQUIPMENT",
    "race": null,
    "class": null,
    "cost": 2,
    "attack": null,
    "defense": null,
    "abilities": [],
    "text": "—",
    "rarity": "COMMON",
    "image_url": null,
    "effects": [],
    "default_unlocked": true,
    "is_active": true,
    "collection_id": "goblin",
    "visual_auras": []
  },
  {
    "id": "gbl_068_idolo_de_madeira_podre",
    "name": "Ídolo de Madeira Podre",
    "type": "EQUIPMENT",
    "race": null,
    "class": null,
    "cost": 3,
    "attack": null,
    "defense": null,
    "abilities": [],
    "text": "—",
    "rarity": "COMMON",
    "image_url": null,
    "effects": [],
    "default_unlocked": true,
    "is_active": true,
    "collection_id": "goblin",
    "visual_auras": []
  },
  {
    "id": "gbl_069_balao_de_observacao_instavel",
    "name": "Balão de Observação Instável",
    "type": "EQUIPMENT",
    "race": null,
    "class": null,
    "cost": 4,
    "attack": null,
    "defense": null,
    "abilities": [],
    "text": "—",
    "rarity": "COMMON",
    "image_url": null,
    "effects": [],
    "default_unlocked": true,
    "is_active": true,
    "collection_id": "goblin",
    "visual_auras": []
  },
  {
    "id": "gbl_070_trono_de_ossos_de_rei_goblin",
    "name": "Trono de Ossos de Rei Goblin",
    "type": "EQUIPMENT",
    "race": null,
    "class": null,
    "cost": 7,
    "attack": null,
    "defense": null,
    "abilities": [],
    "text": "—",
    "rarity": "COMMON",
    "image_url": null,
    "effects": [],
    "default_unlocked": true,
    "is_active": true,
    "collection_id": "goblin",
    "visual_auras": []
  }
] as any;
